### ISSUE TITLE
mongodb-org-tools unmet dependencies in dockerfile

### ISSUE THREAD

**Issue by thebleucheese** [SecurityRiskAdvisors/VECTR#1]
Operating System: Mint 18 Sarah
docker-compose version 1.15.0, build e12f3b9
VECTR Release Version: ce_1.0.0b_20170214

*Due to this error when running docker up:*
```The following packages have unmet dependencies:
 mongodb-org-tools : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'tomcat' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y apt-utils mongodb-org-tools=3.2.11' returned a non-zero code: 100
```

*I had to modify `dockerfile`*
```
>>> DOCKERFILE
RUN apt-key ...
RUN wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb && dpkg -i libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb
```
*Last line added after apt-key line*

This addition is noisy so non-interactive may be better, but this fixed the issue for me.  I also changed the mongodb to 3.2 in the dockerfile to get the latest 3.2 version which didn't seem to have any negative impact on the functionality of the web app.

**Comment by core-dump-19700101** [comment]
Thanks for the info!

We confirmed the issue and will add your solution to the next community release.

**Comment by core-dump-19700101** [comment]
Changes are added to Dockerfile for tomcat image.
