### ISSUE TITLE
Not finding technique while creating assessment

### ISSUE THREAD

**Issue by f1r3walled** [SecurityRiskAdvisors/VECTR#100]
Hey, guys!
Sorry! Maybe the question is quite dumb, but why while creating a new assessment or even a test case, I could not find anything related to the technique Impact, most specifically Data Manipulation (T1565) and the respectives sub-techniques?
Do you know why? Will I need to manually create it?

Cheers!

**Comment by thebleucheese** [comment]
What VECTR version are you using? Impact techniques should be present in more recent versions (5.7+)

If you start typing the name in the Technique field the Data Manipulation techniques should be present.
![image](https://user-images.githubusercontent.com/30511683/99306617-68136500-2823-11eb-9b80-883dd9430c7d.png)

**Comment by f1r3walled** [comment]
I think I got it...
I just needed to create some new test cases associated to those technique and sub-techniques (T1565, T1565.001, T1565.002 and T1565.003). 
I am using the version 6.0.2, but I was expecting to see some test cases automatically created and linked to a default organization (SRA, MITRE, Atomic Red Team), just like other previously existing test cases.
So, I am assuming that sometimes you will need to create new test cases associated to your organization.
Did you get my point? Am I right?

**Comment by thebleucheese** [comment]
Yes, that's correct.  
Atomic Red doesn't look like they have anything for 1565 (you can import their combined index.yaml file in the Administration -> File Import section if they update to include procedures for those Techniques).

The data we (SRA) include with VECTR is a sample of some of the procedures we run during Purple Team engagements so it's non-exhaustive and may require external tools or knowledge.

MITRE CTI does have some data that covers these techniques.  You can import the MITRE enterprise-attack JSON from here (https://github.com/mitre/cti/blob/ATT%26CK-v7.2/enterprise-attack/enterprise-attack.json) in the Administration -> File Import section and then select FIN4 and click submit to import that campaign.  FIN4 uses Stored Data Manipulation.  Some other groups use 1565.x techniques as well.  Note that v7.2 is the latest Mitre ATT&CK version supported by the current VECTR version.  We're working on a new release that should be completed this week to support ATT&CK version 8.0 and 8.1. 

With FIN4 imported you'll have a test case that looks like this:
![image](https://user-images.githubusercontent.com/30511683/99399830-2ed70580-28b4-11eb-94a6-4fcdb7319ad1.png)

**Comment by f1r3walled** [comment]
Crystal clear! :)
