### ISSUE TITLE
Import Atomic Red Team Test Cases

### ISSUE THREAD

**Issue by clr2of8** [SecurityRiskAdvisors/VECTR#103]
I want to update the Atomic Red Team test cases to match the latest from the Atomic Red Team repo so I imported this file https://github.com/redcanaryco/atomic-red-team/raw/master/atomics/Indexes/index.yaml and there were no errors but I don't see any of the new data that got imported. I expect to see all the new test cases that are in the Atomic Red Team repo now as well as the new sub-technique numbering structure.

![image](https://user-images.githubusercontent.com/22311332/103103625-92550100-45df-11eb-8c3c-faaa5db182ab.png)

I click submit and get this message:

![image](https://user-images.githubusercontent.com/22311332/103103633-a436a400-45df-11eb-855a-be72eebdb36f.png)

**Comment by carlvonderheid** [comment]
Hi, thanks for bringing this to our attention.  I confirmed this as a bug, it looks like the new pre-attack mappings for resource-development and reconnaissance were missed in the backend processing.  We will fix this in a release in early January.  In the meantime, if you use an index without the pre-attack merge (or delete all the  resource-development and reconnaissance from the index you tried) it should work.

**Comment by clr2of8** [comment]
Awesome, thanks for posting the work around and excited to try to fix in January.

**Comment by carlvonderheid** [comment]
This should be fixed in 6.1.0, but it looks like no test cases are generated for resource-development and reconnaissance, as Test Cases are generated from the "atomic_tests".
