### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jcleary47** [SecurityRiskAdvisors/VECTR#104]
Hello, I'm running through the initial dependency installation steps for VECTR on a RHEL 7 box. 

**I can run this command successfully:** 
`sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo`

**But when I run this command:**
`sudo yum install docker-ce git unzip wget`

**I get a 404 error:**
_https://download.docker.com/linux/centos/docker-ce.rep/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found_

When I pull that URL up that it is trying to reach out to, it does appear there is nothing there (It looks like the docker-ce.rep directory is not there). 

Am I missing something in a configuration file to point it to a different URL or is something broken elsewhere?

**Comment by SRAPSpencer** [comment]
Docker has recent reorganized their repositories making our instructions no longer valid. Since they didn't have any official communication on the change I'll need to do some research to see what the new commands should be.

**Comment by SRAPSpencer** [comment]
@jcleary47 After doing more research it seems Docker never resolved the issue with their repository. At this time the official Docker method to install Docker-ce on RHEL7 is not functional. This is unfortunately beyond the scope of the assistance we can provide. 

See https://github.com/docker/for-linux/issues/1111 for the status of this issue as it has generated much discussion. There are potential workarounds in the thread but we can't support those. If you needed assistance with Ubuntu installs we would be able to assist more easily.

**Comment by jcleary47** [comment]
> @jcleary47 After doing more research it seems Docker never resolved the issue with their repository. At this time the official Docker method to install Docker-ce on RHEL7 is not functional. This is unfortunately beyond the scope of the assistance we can provide.
> 
> See [docker/for-linux#1111](https://github.com/docker/for-linux/issues/1111) for the status of this issue as it has generated much discussion. There are potential workarounds in the thread but we can't support those. If you needed assistance with Ubuntu installs we would be able to assist more easily.

No problem, I appreciate you getting back to me! I was able to work around the issue by modifying the URL paths that it was using to pull down the data it required, so I was able to get docker installed and also VECTR. 

Awesome tool, love what it has to offer!
