### ISSUE TITLE
Missing Techniques [Red Team Details] - Domain Account - T1087.002

### ISSUE THREAD

**Issue by gregohmyeggo** [SecurityRiskAdvisors/VECTR#107]
The "Technique" list under "Red Team Details" is not populated ["Domain Account" - T1087.002](https://attack.mitre.org/techniques/T1087/002/). 

![2021-01-11 09_26_23-Window](https://user-images.githubusercontent.com/12466798/104216651-2d771480-53ef-11eb-88e2-6cb99cdc61c6.png)

It works when manually setting the MITRE ID in the properties section.

**Comment by gregohmyeggo** [comment]
Running VECTR version: 6.0.3

**Comment by carlvonderheid** [comment]
Thanks for bringing this to our attention!  We will add this to our list to fix.

**Comment by carlvonderheid** [comment]
Should be fixed in 6.1.1, thanks for bringing this to our attention.
