### ISSUE TITLE
Potential DB Mismatch Bug

### ISSUE THREAD

**Issue by 4b4dd0n** [SecurityRiskAdvisors/VECTR#110]
Hey guys! Awesome tool.
I recently upgraded from 6.0.3 to 6.1.4 and I believe I have encountered a bug.
On the side panel when I select either "Vendor & Tools", "Defensive Layers", or "Source IP's" I am redirected to the wrong DB. It is also always the same one. So I am unable to navigate to anything other than that one DB. I am also unable to access GoldStandard. 

Thanks to the API (thanks for adding!) I can determine my DBs are all still there and uncorrupted. I just cannot edit/access them through the GUI.

Assessments and Reporting are both working completely fine without issue.

Please let me know if there is any other information I can provide.

**Comment by carlvonderheid** [comment]
Yes, we have encountered that as well.  We have a fix in place and are testing.  We should have release addressing this by the end of the day.  Thanks!

**Comment by 4b4dd0n** [comment]
Awesome dude! Thank you so much. 
And thank you for creating such a fabulous tool!

**Comment by carlvonderheid** [comment]
Fixed in 6.1.5, let us know if you encounter any additional problems, thanks!
