### ISSUE TITLE
Atomic Red .yaml File Import

### ISSUE THREAD

**Issue by vikinglumberjack** [SecurityRiskAdvisors/VECTR#111]
When attempting to import index.yaml for Atomic Red updates, I get an error message: "No Content Generated". I've tried it using different browsers, but I always get a variant of the same error message. It appears to upload fine, but fails when I hit submit.
![error](https://user-images.githubusercontent.com/8934908/106943101-fc8ab680-66f2-11eb-8760-851e9cc0dd09.png)

**Comment by carlvonderheid** [comment]
What version of VECTR are you running?

**Comment by carlvonderheid** [comment]
I just revisited this on the latest version of VECTR:
https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-6.1.7
and the latest Atomic Red index:
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/Indexes/index.yaml
and was able to import without problems.  

![image](https://user-images.githubusercontent.com/34772348/107508665-61209800-6b6f-11eb-920b-f81f21c43bbd.png)

My guess is you're either on an older version of VECTR, or are not using the 'main' index.yml:

![image](https://user-images.githubusercontent.com/34772348/107508571-3cc4bb80-6b6f-11eb-9dfc-70911724967f.png)

Feel free to open a new issue if you're still having problems.
