### ISSUE TITLE
MITRE ICS Support

### ISSUE THREAD

**Issue by rvn5113** [SecurityRiskAdvisors/VECTR#112]
I made a new MITRE ICS Kill chain however, how can I edit the phase such as "Inhibit Response Function" or "Impair Process Control" to a custom tactic that isn't on the "MITRE tactic" dropdown? I am only able to map the phase to enterprise MITRE tactics.

**Comment by thebleucheese** [comment]
We don't currently support the MITRE ICS tactics in VECTR. We'd love to do so eventually, but we currently build a lot of the functionality in VECTR from structured data presented by MITRE. Currently that data is very mature for the Enterprise ATT&CK matrix, but it's not quite yet for the ICS matrix. 

I'll add this as a feature request so we can look at it in more detail.

**Comment by carlvonderheid** [comment]
ICS and Mobile framework support released in 8.2.0
