### ISSUE TITLE
Question about Import File

### ISSUE THREAD

**Issue by cristiancamps93** [SecurityRiskAdvisors/VECTR#113]
I'm trying to import Mitre Caldera and RedCanary abilities into Vectr by using the import data option (json and yaml files).

However, it returns an error "File Format Invalid or Not Supported".

Does anybody know how to import all Mitre Caldera / RedCanary abilities automatically?

Thanks in advance

**Comment by cristiancamps93** [comment]
![imagen_2021-02-12_153841](https://user-images.githubusercontent.com/14968196/107781627-61c05680-6d48-11eb-92de-414057284527.png)

**Comment by thebleucheese** [comment]
Hey Cristian, 
This file is the only Atomic Red team file import format supported: 
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/Indexes/index.yaml
It's the complete index of all the atomic data from Red Canary.

We don't currently support importing MITRE Caldera data formats.

**Comment by cristiancamps93** [comment]
Thanks a lot!
