### ISSUE TITLE
Error on installation instructions

### ISSUE THREAD

**Issue by MrOrOneEquals1** [SecurityRiskAdvisors/VECTR#114]
I think there might be an error on the instructions for installation.  The wget command does not work as in the instructions. I think the -O should be a -P.

wget https://github.com/SecurityRiskAdvisors/VECTR/releases/download/ce-6.1.7/sra-vectr-runtime-6.1.7-ce.zip -O /opt/vectr

Thanks for taking a look.

**Comment by SRAPSpencer** [comment]
Thanks for the feedback! I'll be sure to get this in on the next update to the documentation.

Paul
