### ISSUE TITLE
Display statistics about logged events in reports

### ISSUE THREAD

**Issue by martindube** [SecurityRiskAdvisors/VECTR#118]
Hi!

I couldn't find a way to display stats about how many tests were logged. I would like to extract this data to demonstrate if a campaign could, in theory, be reconstructed by a Blue Team.

If it doesn't exist, I think that it could be a good addition to the Reporting -> Metrics view. 

Thank you,

**Comment by carlvonderheid** [comment]
Yes, this is actually on our roadmap.  Initially we might provide an "Advanced Filter" where you can select all test cases that are Logged, which will then only display Logged items throughout all the reporting pages.  We are still designing the longer term solution to be able to give users the ability to configure what gets displayed in the pie wedges of the Metrics page (various combinations of outcome / logged / alarmed, etc.

If you wanted to get a list of Test Cases Logged in the meantime, you can always do a csv dump (top right corner, DB icon), then filter by Activity Logged.

**Comment by carlvonderheid** [comment]
This is partially fixed in 7.1.1.  You can select Logged as a sub-outcome to show only those test cases, but it will not draw new pie wedges.  I'll keep this open until fully resolved.

**Comment by SRAPSpencer** [comment]
This has been resolved as part of 8.4.2

https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-8.4.2
