### ISSUE TITLE
Multiple usernames

### ISSUE THREAD

**Issue by siffo** [SecurityRiskAdvisors/VECTR#12]
Is it possible to add multiple usernames (e.g. admin2) to the application? I can see that single admin user is stored in MongoDB. I didn't find any documentation about this.

**Comment by thebleucheese** [comment]
Hi, good timing!  We have a community release coming shortly (within the next day or two) that has a UI for local user management.  There are API operations in place for this, they just aren't exposed in the current community release, which will be addressed in the upcoming version.

**Comment by siffo** [comment]
@thebleucheese I tried the newest version with new clean instance, but there's seems to be some CAS related issues with it. After clean install the CAS failed to recognize linked application, after modifying `"serviceId" : "https://sravectr.internal:8081/sra-purpletools-webui/app\\?client_name=CasClient",`
 to 
`"serviceId" : "^https?://.*",`

It went a little further.

It seems to be able to auhenticate, but in the end fails with message (with default credentials):
"Invalid service ticket. It was either unrecognized or has expired."

Is there way to overcome this issue?

**Comment by carlvonderheid** [comment]
Can you try in a new incognito window?

**Comment by siffo** [comment]
never mind, issue was that the sravectr.internal was missing from local /etc/hosts -file. Once added, the authentication works as intended.
