### ISSUE TITLE
support of new versions of mitre att&ack entreprise

### ISSUE THREAD

**Issue by mahdialibi** [SecurityRiskAdvisors/VECTR#120]
Hi, thank you for the great tool Vectr.
I am using it in our organization to track our coverage for mitre att&ck technics principally with redcanary atomics.
what i noticed is that the heat map is V4 of mitre attack , do you plan to migrate to the latest mitre attack matrix ?
Thank you

**Comment by carlvonderheid** [comment]
Hi, can you explain what functionality you are looking for?

We are currently using:
   ATT&CK Navigator Layer File Format v4
   ATT&CK v8, specifically v8.2 of MITRE CTI

The ATT&CK Navigator v4.1 added an optional 'divider' field, which we do not leverage.
The ATT&CK Navigator v4.2 did not change the Layer File Format

**Comment by mahdialibi** [comment]
Thank you for the clarification , it was a mistake from me I haven't seen that is v8.2 of Mitre CTI
