### ISSUE TITLE
VECTR 6.2.1 fails to add Mitre layer v8.0 reconnaissance part

### ISSUE THREAD

**Issue by TickledBlueB** [SecurityRiskAdvisors/VECTR#121]
Hello everyone!

I was trying to use mitre db on vector and one issue occures: cannot import "reconnaissance" part of the layer. All other works fine... Any ideas?

Tehnical info: VECTR update to 6.2.1 - Mitre Navigator (https://mitre-attack.github.io/attack-navigator/) v8.0 Reconnaissance (failed .sjon file) and Initail Access (works).

**Comment by carlvonderheid** [comment]
I don't think the functionality is broken.  By default there are no templates shipped in VECTR with a phase of "Reconnaissance" and a TechniqueID mapped to an item in the Attack Matrix.  I changed the techniqueId and Phase to match one in the matrix:
![image](https://user-images.githubusercontent.com/34772348/112869796-8d469880-908b-11eb-8168-17084ec5c7cb.png)

Then created a Layer with all Recon techniques selected:
![image](https://user-images.githubusercontent.com/34772348/112869983-b9fab000-908b-11eb-8c01-559bdf8d084d.png)

and that made my modified Test Case show up in my Assessment using "From Nav Layer".

**Comment by carlvonderheid** [comment]
Let us know if you're still having problems
