### ISSUE TITLE
API not pulling tag information

### ISSUE THREAD

**Issue by OffsecChuck** [SecurityRiskAdvisors/VECTR#123]
Can not get the API to return any tag data { id, name, tagColor } from any section of the API.
Can determine there are tags by counting the number of empty vs null returns. 
Have read all of the schema, examples, etc with no luck. 

'{"query":"query { assessment(db: \\"Database\\", id:\\"an id\\") { id, name, tags {id, name }}}","variables":{}}

Returns "tags" : []  or  "tags": [None,None]

Read the wiki, manuals, etc and haven't found a work around to pull tags with the API.

**Comment by carlvonderheid** [comment]
Thanks for finding this, confirming as a bug.  We will fix in the next release.

**Comment by carlvonderheid** [comment]
Fixed in version 6.2.2
