### ISSUE TITLE
Heatmap information - "Detected" results indicate "Logged: TBD"

### ISSUE THREAD

**Issue by gregohmyeggo** [SecurityRiskAdvisors/VECTR#126]
Under the assumption that a Test Case is "Detected" the Heatmap returns this with a "Logged: TBD" result. Based on these results, shouldn't the Heatmap indicate that the events were in fact "Logged: Yes" due to the generation of an alert?

**Comment by carlvonderheid** [comment]
Fixed in 7.1.1
