### ISSUE TITLE
Issue importing Navigator ATT&CK json

### ISSUE THREAD

**Issue by the2dl** [SecurityRiskAdvisors/VECTR#129]
Hello,

I tried to import a Conti ransomware Navigator json file (file is located here > [Conti Navigator](https://raw.githubusercontent.com/scythe-io/community-threats/master/Conti/Conti_ATT%26CK_Navigator.json)

I was on VECTR v6 and it just said it didn't support nav layer 4.2, so I upgraded to VECTR v7.0.0 and now I get a different error message (attached below).

![Screen Shot 2021-05-26 at 8 15 39 AM](https://user-images.githubusercontent.com/51533129/119658034-ac974300-bdfa-11eb-9bf6-ef9194a8cc53.png)

Is there something I can modify to make this import? I tried to tweak a few settings in the json but ended up with more programatic errors.

Thanks!

**Comment by carlvonderheid** [comment]
I don't think "mitre-enterprise" is a valid domain.  From the Layer Format documentation (https://github.com/mitre-attack/attack-navigator/blob/master/layers/LAYERFORMATv4_2.md):
![image](https://user-images.githubusercontent.com/34772348/119660457-495ae000-bdfd-11eb-8574-5ecc3affb263.png)

You can try to change:
"domain": "mitre-enterprise" 
to
"domain": "enterprise-attack"

**Comment by the2dl** [comment]
Yeah, that's the thing I tested - I end up with the error message below >

![Screen Shot 2021-05-26 at 8 44 22 AM](https://user-images.githubusercontent.com/51533129/119661773-a30fda00-bdfe-11eb-9250-06b82303fe50.png)

Perhaps the file has some other issues in it.

**Comment by carlvonderheid** [comment]
Change:
`"version": "4.2",`
to
`"versions": {
		"attack": "9",
		"navigator": "4.3",
		"layer": "4.2"
	},`

**Comment by the2dl** [comment]
Fantastic! Thank you for the assist, imported and working great.
