### ISSUE TITLE
Campaign Templates > New Campaign Button Doesn't Work

### ISSUE THREAD

**Issue by gregohmyeggo** [SecurityRiskAdvisors/VECTR#132]
On VECTR v6.2.2, the New Campaign button under Campaign Templates does not prompt the 'creation window', but automatically produces a popup that says 'Cancelled'. This occurs with a user account, but also the Admin role as well. 

Administration > Campaign Templates > New Campaign

**Comment by carlvonderheid** [comment]
I'm not seeing this on our side...can you send a contact email to vectrops@securityriskadvisors.com and we will be in touch to take a look?
