### ISSUE TITLE
heatmap unable display detected rules

### ISSUE THREAD

**Issue by G4rb3n** [SecurityRiskAdvisors/VECTR#135]
![image](https://user-images.githubusercontent.com/19891095/124921542-17a77c80-e02b-11eb-9fba-45ccc68db2fa.png)

![image](https://user-images.githubusercontent.com/19891095/124921519-124a3200-e02b-11eb-801f-0dc9149cdc2f.png)

**Comment by carlvonderheid** [comment]
Fixed in 7.1.1

**Comment by G4rb3n** [comment]
it's ok, thx
