### ISSUE TITLE
Phases,  Organization, Rules, Behaviors have not 'delete' button

### ISSUE THREAD

**Issue by G4rb3n** [SecurityRiskAdvisors/VECTR#136]
![image](https://user-images.githubusercontent.com/19891095/125254245-dc5bc500-e32c-11eb-899a-412ac118ae0f.png)

**Comment by carlvonderheid** [comment]
dup of #75

**Comment by thebleucheese** [comment]
In recent VECTR versions, non-system rules, behaviors, phases, and orgs can be edited and deleted.
