### ISSUE TITLE
Tags missing after DB migration

### ISSUE THREAD

**Issue by fuckup1337** [SecurityRiskAdvisors/VECTR#138]
Hello,

because I had to move vectr to another machine, I migrated my DB from 6.0.1 to 7.0.2 using the json and bson files and stored them in /opt/vectr/user/mongo

The database was migration was successful but for some reason I dont have tags anymore - furthermore i can not create new ones - if i go on tagging i can create one but they will not be saved or appear on the assessment / testcase. 

Any idea how to fix that? 

Thanks!

**Comment by SRAPSpencer** [comment]
It doesn't sound like an issue we're familiar with. 

Can you dump your logs from the Tomcat container? Depending on if you set custom container names it should be something like. 

`docker logs sandbox1_tomcat_1`

Look for anything with warning or exception in the migration logs, most of them are pretty clearly labeled. We'll likely need to assist manually to resolve the issue, but getting the logs ahead of time would be helpful. 

Paul

**Comment by fuckup1337** [comment]
I can not see anything special - just tag not found errors. 
I also tried to manually import the db using mongorestore but this is exactly the same. 

In which part of the DB are the tags stored?

**Comment by fuckup1337** [comment]
just found out if I create a new Assessment I can create tags which will be saved. But I can not attach them to the imported ones

**Comment by fuckup1337** [comment]
strange thing is also that the db on the old instance is 0.001GB bigger than the imported one

**Comment by carlvonderheid** [comment]
They're in the GoldStandard database. Is that included in your user/mongo directory to load?

**Comment by fuckup1337** [comment]
that was it

Thanks for the quick help!
