### ISSUE TITLE
Issue with docker-compose support on Ubuntu & RHEL

### ISSUE THREAD

**Issue by RBarui** [SecurityRiskAdvisors/VECTR#140]
Used apt-get to install requirements (docker-ce, docker-ce-cli, containerd.io, docker-compose, unzip) on Ubuntu (GCP).

But while trying to run **docker-compose up -d** , I am getting issues with the docker-compose version.

**ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.**

Changed docker-compose.yml file and padded version to 2. 
But now getting a different issue
**ERROR: Invalid interpolation format for "ports" option in service "tomcat": "${VECTR_PORT:-8081}:8443"**

**Comment by thebleucheese** [comment]
Did you add the docker apt repo from the instructions here first? https://docs.vectr.io/Installation---Ubuntu/ The docker-compose version in Ubuntu’s default apt repo is very out of date and will cause problems.

**Comment by RBarui** [comment]
Hi,
I followed https://docs.vectr.io/Installation---Ubuntu/ only. Also tried to follow some other ways from StackOverflow. But it's not solving the issue.

**Comment by thebleucheese** [comment]
The error you’re getting is stating that your docker-compose version is outdated. Any modern version of the docker-compose script will support higher than version 2 so your system is still trying to access an older version of the script. 

You could try removing the old docker-compose and any other conflicting docker-compose files in your system PATH before installing the new version. It’s possible you could have one in your usr/local/bin or a bin folder in your home directory that was installed manually or by other software.

**Comment by RBarui** [comment]
Yes, I am presently trying to flush the system and do a barebone docker install first. Then will install VECTR. Let's see the outcome then.
Thanks 👍🏽
