### ISSUE TITLE
Title Bar Incorrect, "Assessment" should be "Test Cases"

### ISSUE THREAD

**Issue by clr2of8** [SecurityRiskAdvisors/VECTR#145]
![image](https://user-images.githubusercontent.com/22311332/134421821-cda59e99-ca01-4fba-a443-54da31eaa6b6.png)

**Comment by SRAPSpencer** [comment]
Nice catch @clr2of8 ! We'll get this typo fixed.

**Comment by doodleincode** [comment]
Fixed in [ce-8.1.0](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-8.1.0).
