### ISSUE TITLE
Update Mitre Information

### ISSUE THREAD

**Issue by ssnkhan** [SecurityRiskAdvisors/VECTR#16]
Would it be possible to update the Mitre datasets to reflect the recent changes published in April 2019 please? This adds 14 new techniques within a new phase amongst other changes; including 'Impact'. More information is detailed here:

https://attack.mitre.org/resources/updates/updates-april-2019/index.html

I have tried to go into Administration > Kill Chains but the Edit button is greyed out. I was able to add the Phase via the Phases Menu.

Also thought it would be worhwhile to load the Mitre PRE-ATT&CK and Mobile frameworks as part of the default installation?

**Comment by carlvonderheid** [comment]
The new Mitre Tactic "Impact" and the heatmap have been updated in version 5.1.4.  Note, this is a maintenance release, so you'll just need to copy wars in the release package into your existing <VECTR_DEPLOY_DIR>/wars directory.  Also copy the sra-vectr-root.zip/config/datasets.mitre-cti.json to <VECTR_DEPLOY_DIR>/config/datasets/
