### ISSUE TITLE
Group membership incorrectly reflects deleted users

### ISSUE THREAD

**Issue by initstring** [SecurityRiskAdvisors/VECTR#166]
**Describe the bug**

I recently deleted a handful of local user accounts. They belonged to various groups. Now, under "Access Management -> Groups", the "Users" column shows an incorrect number which I am assuming included the deleted users.

**To Reproduce**
1. Add a test user account
2. Add that user to a user group
3. Delete the user
4. See that the number of users in that group does not go down, although they are no longer in the actual list

You end up in a situation where you can edit the group and count the list of users, and then see that count does not match what is reflected in the summary view.

**Expected behavior**

The number should decrement when a user is deleted.

**Screenshots**
You can see here the tool reports 9 users in the group, but there are only 5 members in there when I go to edit it.
![1](https://user-images.githubusercontent.com/26131150/154166971-997f5607-e022-4792-b524-6de6db6d4df7.png)
![2](https://user-images.githubusercontent.com/26131150/154166985-3224f284-0ac0-4943-ac71-30d248e585f5.png)
![3](https://user-images.githubusercontent.com/26131150/154166996-1a2984af-8873-4183-91b8-6c738f3694bc.png)

**Desktop (please complete the following information):**
 - Kubuntu
 - Firefox v96

**Comment by doodleincode** [comment]
Thanks for reporting this! Can confirm as a bug, we'll get it fixed in a future release.

**Comment by carlvonderheid** [comment]
Fixed in 8.5.1
