### ISSUE TITLE
v8.2.2 - Imported Atomic Red Team executor setting ignored, commands don't match "Operator Guidance"

### ISSUE THREAD

**Issue by clr2of8** [SecurityRiskAdvisors/VECTR#170]
I imported the latest index.yaml from Atomic Red Team. When I used the "Automation & Logging" feature, the executor for this Windows test was set to "sh" which leads to an error during execution. 

![image](https://user-images.githubusercontent.com/22311332/156023832-8a2b6fd4-350b-4ce1-b39c-d8303a29d0af.png)

![image](https://user-images.githubusercontent.com/22311332/156023902-f70399de-5a33-4cf4-bee4-8c9c0d0d1908.png)

If I go into "Configure", I see that the executor is set to "sh" (should be CMD) and the Commands are Linux commands from another test completely and don't match what is in the Operator Guidance Section.

Actually, I noticed there are two versions of this test. One has this issue and one doesn't. I think one comes packaged with VECTR and one is the one I just imported. 

![image](https://user-images.githubusercontent.com/22311332/156029389-5514222e-6063-45f3-8eaf-ef9489206a21.png)

**Comment by SRAPSpencer** [comment]
Thanks for pointing this out. This data actually exists in the instance before the Atomic Red is imported, hence the lack of "ART" at the beginning of the test case. 

We're working on updating the shipping datasets for VECTR which should address some of these issues. It is a larger than expected technical lift to accomplish this so no ETA at this time. Hopefully in a release in the not too distant future.

**Comment by SRAPSpencer** [comment]
This has been resolved by Release 8.4.2
