### ISSUE TITLE
Portainer Support

### ISSUE THREAD

**Issue by krsecurity** [SecurityRiskAdvisors/VECTR#171]
**Describe the bug**
404 page on initial install

**To Reproduce**
Build on docker using portainer.

**Expected behavior**
For the platform to work

**Screenshots**
![image](https://user-images.githubusercontent.com/79098696/156561746-4fbe8b8a-b2be-41fc-8d23-b469b82f8375.png)

**Desktop (please complete the following information):**
Server running on Ubuntu docker swarm with portainer overlay

**Additional context**
Looks like /auth/api/v1 failures within tomcat logs:

![image](https://user-images.githubusercontent.com/79098696/156561831-847c7a8e-2b05-4440-8e47-c5860a630cc5.png)

The api folder doesn't even appear to exist!

![image](https://user-images.githubusercontent.com/79098696/156561881-74e3bf64-a243-406e-bd1c-4a6354af261c.png)

Possibly i'm missing some steps here.

Thanks

**Comment by krsecurity** [comment]
This looks like a problem with the auth.war file and possibly the Mongodb from a little further investigation.

**Comment by SRAPSpencer** [comment]
Hello, we currently don't support k8s/swarm in community edition. CE is tested and validated on single host docker installs with docker-compose setting up the environment. I'm also not sure about Portainer's platform and the way it handles compose files. Skimming this article https://www.portainer.io/blog/stacks-docker-compose-the-portainer-way it seems to suggest you can load one but I'm not sure it's 100% compliant. 

If you have any other findings you're more than welcome to post them here but our capacity to help on unsupported platforms with CE is limited. I'd suggest following the getting started guide on the docs https://docs.vectr.io/Installation/ or reaching out to us directly if you have an enterprise use case for k8s/swarm.

**Comment by krsecurity** [comment]
> 

Hi - I have deployed on a single host as well with the same issue. It is using portainer/docker swarm but with constraints so that all containers are spun up on the same host.

**Comment by SRAPSpencer** [comment]
Beyond the single host configuration it's still hard to say without being more familiar with portainer. My biggest doubt is that it's actually 100% docker compose compliant. It's such a greenfield issue on unsupported tools it's difficult to deduce where to start. Here's some things to check.

Is the networking being deployed correctly? The auth war getting an error 400 might mean it can't resolve container names. Try jumping into a container and pinging the others. 

Does it consume the .env file as well as the docker compose? If you jump into the container can you check the running variables for matches to your set values?

Can you see if any data is being written to the tomcat container? We've also had issues with file permissions on container volumes. If certain configuration files can't be created on startup that could also cause issues.

**Comment by SRAPSpencer** [comment]
Small update here.

In a brief session looking at this issue in a Portainer environment, Portainer does not respect Volumes or Network information in the docker-compose. As suspected Portainer isn't actually docker-compose compliant and just discards large amounts of the information in the file. Not likely to be addressed by the VECTR team in the near future.

**Comment by thebleucheese** [comment]
VECTR application has unified services and standardized container & volume use since this ticket was opened and could possibly work in an environment like this, but we don't have plans to directly ensure Portainer compatibility.
