### ISSUE TITLE
mongdb is not working 

### ISSUE THREAD

**Issue by alishwani** [SecurityRiskAdvisors/VECTR#177]
Hi Team, I am having issue with migrating Vectr to the latest version. In process of doing so, I am receiving an issue that Mongodb server is stuck in "Restarting" point.

**Comment by alishwani** [comment]
<img width="889" alt="Upgrading_issue" src="https://user-images.githubusercontent.com/33989965/168670777-0de96756-a048-4b5a-893c-2854e59b5d46.PNG">

**Comment by SRAPSpencer** [comment]
What version were you trying to upgrade from?

What version of Ubuntu is this?

**Comment by alishwani** [comment]
Then when I go the link it goes me status code 404 
<img width="958" alt="error" src="https://user-images.githubusercontent.com/33989965/168670934-e3cbe382-1dd6-474d-a46e-77b8f051fe76.PNG">

**Comment by alishwani** [comment]
trying to update from 8.0.2

**Comment by alishwani** [comment]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

**Comment by SRAPSpencer** [comment]
It's exiting under code 14, which is usually out of memory or otherwise resource constrained. 

Do you know if the host is out of Disk Space? How much memory does the VM have?

**Comment by alishwani** [comment]
<img width="707" alt="memory" src="https://user-images.githubusercontent.com/33989965/168671541-9d7ef001-249c-40ee-a35a-7c4f856c4af5.PNG">

**Comment by SRAPSpencer** [comment]
Hm, it was working correctly on 8.0.2?

We use the official MongoDB image, so it's not likely a VECTR specific issue. 

I'd try to reboot the VM first, ensure there's nothing strange happening with the docker service. 

The next likely candidate would be file permissions issues. However I do not believe we changed anything from 8.0.2 to latest. So it would be surprising if it stopped working.

**Comment by alishwani** [comment]
Yes, 8.0.2 was working great. But I even upgraded in our nonprod environment and it was all good no issue. when I tried upgrading in the prod environment I get the error.

**Comment by SRAPSpencer** [comment]
I don't have any further recommendations after considering it. It's likely an issue specific to that VM. Something is interfering specifically with the MongoDB container starting. 

I'll leave this open if anyone else has anything to add.

**Comment by alishwani** [comment]
Thank you Paul for looking into this, I will further troubleshoot on my end to see it is possible to get it to work.

**Comment by SRAPSpencer** [comment]
Stale. @alishwani please reopen if you still need assistance with this.
