### ISSUE TITLE
Timeline event deletion non functional

### ISSUE THREAD

**Issue by mk-parrot** [SecurityRiskAdvisors/VECTR#181]
Deletion of timestamps from campaign timeline or the list in a test case does not function.

**To Reproduce**
1. Go to campaign in which test cases have been performed
2. Click on an event in the timeline to edit it
3. Press delete
4. Application returns status code 500 with message `Index 0 out of bounds for length 0`

**Expected behavior**
The event in timeline gets deleted

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox 101.0 & Google Chrome 102.0.5005.61

**Comment by SRAPSpencer** [comment]
This is resolved by the 8.4.2 Release.
