### ISSUE TITLE
Unable to delete Group Templates on Red Hat deployment

### ISSUE THREAD

**Issue by RFC1918-hub** [SecurityRiskAdvisors/VECTR#183]
Deployed Vectr on Red Hat Enterprise Linux Server release 7.9 (Maipo)

Unable to delete group templates from web interface. 

To Reproduce Steps to reproduce the behavior:

Go to Group Template page
Click on Delete Assessment group
**See error**
HTTP 500: Unable to Delete Test Assessment

Screenshots If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/61937657/175517923-d2a09da4-3cc7-455d-bbf5-c2f02997c5db.png)

Docker logs of tomcat container: 
![image](https://user-images.githubusercontent.com/61937657/175518709-f769bf97-a86b-44cb-b487-2fa1797d5989.png)

Desktop (please complete the following information):
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Browser: Edge
Version: Version 102.0.1245.44 (Official build) (64-bit)

**Comment by SRAPSpencer** [comment]
Thanks for reporting. I was able to reproduce and will add to our bug tracker.

**Comment by carlvonderheid** [comment]
Fixed in 8.5.1
