### ISSUE TITLE
Unable to view Test Case Phase via GraphQL API

### ISSUE THREAD

**Issue by inance** [SecurityRiskAdvisors/VECTR#184]
**Describe the bug**
I'm using GraphQL to view TestCase objects, but it does not appear that Phase is available via the API. 

**To Reproduce**
Query GraphQL for TestCase data. Documentation does not show Phase or PhaseID as an available data field.

**Expected behavior**
Would like to be able to gather phase information for test cases when querying through GraphQL.

**Comment by SRAPSpencer** [comment]
Does this provide the information you're looking for?

https://docs.vectr.io/graphql/schema/phase.doc.html

**Comment by SRAPSpencer** [comment]
After discussing with the team we understand the request and have added it to our request tracker.

**Comment by inance** [comment]
Thank you very much. If I can clarify anything, let me know. If it helps: I want to use GraphQL to pull down a list of TestCases from a campaign and organize them by the Phase they were assigned. It is included when exporting a report, but not with GraphQL (unless there's something I'm missing).

**Comment by atropineal** [comment]
+1 for this :)  I'm currently using the API to generate a MITRE ATT&CK navigator JSON file.  Because of the lack of phase data from the GraphQL API,  a TTP associated with more than 1 tactic will be associated with all tactics.  My workaround was to add phase tags to test cases with TTPs that apply to more than 1 tactic.

**Comment by thebleucheese** [comment]
> +1 for this :) I'm currently using the API to generate a MITRE ATT&CK navigator JSON file. Because of the lack of phase data from the GraphQL API, a TTP associated with more than 1 tactic will be associated with all tactics. My workaround was to add phase tags to test cases with TTPs that apply to more than 1 tactic.

@atropineal and @inance this addition to the API (along with the ability to update Test Cases and also pull the Kill Chain data with Assessments) will be in the next release, we're testing internally right now

**Comment by atropineal** [comment]
Woohoo!  And thank you so much for this fabulous tool.

**Comment by doodleincode** [comment]
This has been addressed in [ce-8.6.1](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-8.6.1).
