### ISSUE TITLE
Local Account Access Disrupted && SSO integration for New Vectr Upgrade

### ISSUE THREAD

**Issue by arishwani** [SecurityRiskAdvisors/VECTR#185]
Hi Vectr Team,

I am having an issue where after assigning a dns name hosting vectr on https, some of local account users are getting redirected to the old dns name and port 8081; therefore, leading to an error because the old dns has been removed and the port is https instead of 8081. This issue is only for some users. 

Also, I see there is a new Vectr version " VECTR v8.4.3" does SSO works with this new version. There was an issue with SSO integration for the VECTR v8.3.2. Wondering if the same issue persist for the new version. 

Thank you

**Comment by alishwani** [comment]
@SRAPSpencer Thank you for the reply, since there was a ticket open for this issue https://github.com/SecurityRiskAdvisors/VECTR/issues/178
I did not try setting up SSO; therefore, I am wondering if this specific issue that brought up in this ticket https://github.com/SecurityRiskAdvisors/VECTR/issues/178  is closed with the 8.4.3 version.

**Comment by doodleincode** [comment]
> @SRAPSpencer Thank you for the reply, since there was a ticket opened for this issue #178 I did not try setting up SSO; therefore, I am wondering if this specific issue that brought up in this ticket #178 is closed with the 8.4.3 version.

#178 should be fixed in 8.4.3. We'll close out that ticket.

**Comment by SRAPSpencer** [comment]
> @SRAPSpencer Thank you for the reply, since there was a ticket opened for this issue #178 I did not try setting up SSO; therefore, I am wondering if this specific issue that brought up in this ticket #178 is closed with the 8.4.3 version.

Did @doodleincode answer your question? Let us know if you need further assistance.

**Comment by SRAPSpencer** [comment]
Stale issue.
