### ISSUE TITLE
Toggle Unused Techniques in Heatmap View

### ISSUE THREAD

**Issue by ssnkhan** [SecurityRiskAdvisors/VECTR#19]
In the Heatmap View, it would be helpful to be able to toggle unused Techniques, so as to only view Techniques used in a specific campaign. Currently the system shows all Mitre techniques, with unused ones being greyed out but still being displayed in the grid.

![](https://raw.githubusercontent.com/SecurityRiskAdvisors/VECTR/master/media/VectrMitreHeatmap.png)

**Comment by carlvonderheid** [comment]
You can click cells in the legend to toggle them on/off.  You'll probably want to click the "No Coverage" cell.
