### ISSUE TITLE
SSO Integration Issue

### ISSUE THREAD

**Issue by arishwani** [SecurityRiskAdvisors/VECTR#192]
Hi Team, 
I am having issue with integration VECTR into SSO. The error is "No Reply address was provided". Although, I provided the Reply Address. I tried both AzureAD and SAML but wouldn't work. 

Any recommendation, please? 
<img width="316" alt="VECTR_Issue" src="https://user-images.githubusercontent.com/33989965/190662344-1eb3c25b-f9d5-496b-9a6c-c81d268fb35d.png">

**Comment by SRAPSpencer** [comment]
When you input the SSO IdP into VECTR it will generate a list of URLs, these URLs should be put into the SSO entry under the IdP platform(Azure). 

I'll leave this open but we don't usually offer community support for SSO, see the guidelines. 

https://github.com/SecurityRiskAdvisors/VECTR/issues/146

**Comment by arishwani** [comment]
Hi @SRAPSpencer. Yes, I put those list of URLs into SSO in Azure platform but still won't work? I get the that error.

**Comment by arishwani** [comment]
Yes, I followed those steps as well but didn't work.

**Comment by doodleincode** [comment]
Unfortunately we cannot provide SSO onboarding support to the open community as configuration of SSO with the identity / SSO provider is highly variable as well as differences in organizational level security policies and procedures that can impact how SSO is configured. If you're not already on our Discord channel, I would recommend joining and asking the community for help. https://discord.gg/2FRd8zf728
