### ISSUE TITLE
Download Report not working

### ISSUE THREAD

**Issue by dorianlac** [SecurityRiskAdvisors/VECTR#199]
When downloading report following error was displayed in the console and error 500 was shown.
`vectr-tomcat_1         | 2022-11-04 13:58:31,625 ERROR [org.apache.cxf.jaxrs.utils.JAXRSUtils] - No message body writer has been found for class com.sra.purpletools.rest.response.BasicResponse, ContentType: application/vnd.openxmlformats-officedocument.wordprocessingml.document`

**Comment by SRAPSpencer** [comment]
Can you provide more detail? Such as, 

"If your issue appears to be a bug and hasn't been previously reported, open a new issue with details on how to reproduce the bug. The "new issue" form should include enough information to understand and categorize the issue. Screenshots and log information are helpful."

Also what version of VECTR you're running.

**Comment by dorianlac** [comment]
This issue was detected in version 8.5.1 and in new 8.6.1. Version 8.4.3 is working fine.
Just go Download Report in the assessments section and select in example Timeline Detailed.
![Selection_053](https://user-images.githubusercontent.com/32019493/199997484-e285ac6d-f438-4d51-bcd9-43a1f4f0f499.png)

**Comment by SRAPSpencer** [comment]
I was able to recreate the issue. I'll get this over to the team.

**Comment by carlvonderheid** [comment]
Fixed in 8.6.2
