### ISSUE TITLE
KNOWN ISSUE: Existing API Keys not working in 8.6.1

### ISSUE THREAD

**Issue by thebleucheese** [SecurityRiskAdvisors/VECTR#200]
VECTR 8.6.1 contains a known issue where upgrading from a prior version can cause existing API keys to not work under some circumstances.

A hotfix (8.6.2) is being created to fix this issue with an expected release of tomorrow if testing completes successfully.

If you can not wait for a hotfix, a workaround is to delete all existing API keys and create new ones. If any old / broken API keys are present, you will receive errors.

**Comment by carlvonderheid** [comment]
Fixed in 8.6.2
