### ISSUE TITLE
Running VECTR on WSL2 web app not running

### ISSUE THREAD

**Issue by sepehrn0107** [SecurityRiskAdvisors/VECTR#206]
hi. I've installed Vectr on WSL following the instructions and docker-compose up -d finished sccessfully, but when trying to open the web app, i get the following error:
DNS_PROBE_FINISHED_NXDOMAIN
I found an earlier issue where the problem was solved by adding "127.0.0.1 NAME_OF_HOST" to etc/host which i did with no success. Is it at all possible to run VECTR through WSL2 on windows 10? if so, what would cause this problem?

**Comment by SRAPSpencer** [comment]
VECTR isn't supported on WSL/2. Generally we intend for VECTR to be treated as a server application and shouldnt be run on a desktop. It may have worked in the past but I'm not sure how the networking works between the Linux layer and Windows.

**Comment by sepehrn0107** [comment]
I got it to work by adding "127.0.0.1 APP_NAME" to hosts in windows "system/drivers/etc" to channel through Linux layer as well as doing the same in WSL. This works when running locally
