### ISSUE TITLE
[Feature Request] Capability to update more fields of a test case

### ISSUE THREAD

**Issue by L3houx** [SecurityRiskAdvisors/VECTR#213]
This issue is about a feature request.

**Problem:** I tried to update TestCase by adding tags automatically using Python and GraphQL's API. I am able to update descriptions and other fields but not tags. Currently, these are the fields that are supported for an update (mutation),

```
input UpdateTestCaseDataInput {
        testCaseId: String!
        operatorGuidance: String
        description: String
        outcomeNotes: String
        outcome: String
        outcomeEventTime: String
        outcomeDefenseToolIds: [String!]
        currentStatus: TestCaseStatus
        attackStartTime: String
        attackStopTime: String
    }
```

Reference: https://docs.vectr.io/graphql/schema/updatetestcasedatainput.doc.html

**Goal**: Our goal is to be able to automatically add and remove fields, in this case, tags depending on the progression of a test case. While the test change stated,
- development
- ready to test
- assign the person that worked on that test
- etc.

**Comment by thebleucheese** [comment]
@L3houx the ability to add and remove tags by name in the update test case mutation will be included in the next VECTR release

**Comment by thebleucheese** [comment]
> @L3houx the ability to add and remove tags by name in the update test case mutation will be included in the next VECTR release

VECTR 8.8.0 release contains these additions
