### ISSUE TITLE
Data Conflict after opening a test case sorted by tags 

### ISSUE THREAD

**Issue by L3houx** [SecurityRiskAdvisors/VECTR#216]
## Description
I sorted tags of test cases in a campaign. After I opened a test case with tags (minimum 2). I saw a green line around tags and it keeps flashing. A couple of seconds later, a window popped up with a Data conflict message.

If I open a test case of a campaign without sorting by tags, there is no problem. The problem happens when I sort by tags (up, down, or back to normal sorting). Since I sort tags, the problem appears. I need to refresh the page (without sorting tags) to be able to click on a test case without the "Data Conflict" message. 

## Reproduce the Bug
1- Select an assessment
2- Select a campaign
3- Sort test cases by Tags (up or down)
4- Select a test case with a minimum of 2 tags
5- Wait a couple of seconds (~30)
6- a "Data Conflict - Modified on Server" message pop up

## Expected behavior
I want to be able to sort test cases in a campaign and open one of them without data conflict.

## Screenshots

![image](https://user-images.githubusercontent.com/32520954/219418361-7d057ee3-e7be-454d-8845-06ecd7996786.png)
*Sorting Tags* 

![image](https://user-images.githubusercontent.com/32520954/219418442-24ba76dc-07d6-4b90-acb8-760e101ff1a2.png)
*Tags flashing*

![image](https://user-images.githubusercontent.com/32520954/219418594-548b5776-28b5-4fdf-93c4-f9d8a6eb4f1d.png)
*Data Conflict*

![image](https://user-images.githubusercontent.com/32520954/219418961-bc6f2916-e0cd-48fe-a0a7-e265bc766c4e.png)
*No difference between tags*

**Comment by SRAPSpencer** [comment]
Team is currently backlogged, will attempt to replicate when possible.

**Comment by thebleucheese** [comment]
confirmed that this is a bug, going to try to get a fix in for the next release. thanks for the report

**Comment by thebleucheese** [comment]
Corrected tag sorting bug in 8.8.0
