### ISSUE TITLE
XSS in Campaign test cases

### ISSUE THREAD

**Issue by adm1nPanda** [SecurityRiskAdvisors/VECTR#222]
**Describe the bug**
Found an XSS Vulnerability in the "Edit Test Cases" window.

**To Reproduce**
1. Select a Campaign
2. Click on any test case or create a new test case
3. Enter '<img src=# onerror="alert(1)"/>' into the description field. 
4. invoke XSS by clicking on the View/Edit button when hovering over the same input field

**Expected behavior**
Input should be parsed and XSS shouldn't execute

**Screenshots**
![Screenshot 2023-03-06 121334](https://user-images.githubusercontent.com/14232737/223182339-e99cac40-b37b-4297-81d3-3a08649bf621.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome
 - Version: v8.7.1

**Additional context**

XSS only executes when user browses into edit window and manually clicks on the view/edit button

**Comment by thebleucheese** [comment]
@adm1nPanda thanks for the report, we were able to reproduce and will look into a fix for this ASAP

**Comment by carlvonderheid** [comment]
Fixed in [8.7.2]([url](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-8.7.2))
