### ISSUE TITLE
if mitre Id is added via free text in the UI it does not appear when queried via API

### ISSUE THREAD

**Issue by fuckup1337** [SecurityRiskAdvisors/VECTR#229]
If I create a own Mitre ID (Technique in the Red Team Details). It does not appear when queried with the API. In the UI it shows the one i set manually but when query via API it just says "Null" or just nothing. Seems like I need to create the Techniques somewhere first and select them via drop down. Could you tell me where to set a technique as a quick workaround? 

Might be worth checking why free text does not work in the future. 

Thanks!

**Comment by thebleucheese** [comment]
> If I create a own Mitre ID (Technique in the Red Team Details). It does not appear when queried with the API. In the UI it shows the one i set manually but when query via API it just says "Null" or just nothing. Seems like I need to create the Techniques somewhere first and select them via drop down. Could you tell me where to set a technique as a quick workaround?
> 
> Might be worth checking why free text does not work in the future.
> 
> Thanks!

Click the cog in the upper right of "Red Team Details" in the Test Case panel. There's another dialog that will show Mitre ID. Mitre ID and Technique are 2 separate data points. They're linked so if you select from the auto-complete list it should populate the other field, but you can also manually enter data in "Technique". If you manually enter data in Technique, nothing will show in Mitre ID. This is reflected in the results of the GraphQL API.

This isn't the most intuitive so it's being taken into consideration as we redesign various UI screens. I'm closing this for now, but feel free to reopen, ask about it on discord, or @ me if you run into any further issues.

**Comment by fuckup1337** [comment]
thx! will give it a try
