### ISSUE TITLE
[X]Verify extracted VECTR release

### ISSUE THREAD

**Issue by qq854051086** [SecurityRiskAdvisors/VECTR#23]
[X]Verify extracted VECTR release
 ERROR: VECTR Deployment can not continue. Please correct any issues marked above or check installation logs.

Can you tell me how to solve it?

**Comment by thebleucheese** [comment]
Hi, can you provide the following information so we can help diagnose the issue?

- Are you performing a fresh VECTR install or an upgrade of an existing installation? 

- Installation target operating system?

- User account permissions used when installing (are you running as sudo?)

- Are there any other error messages seen in the console output during installation aside from the one you marked above?

- Please provide log file entries surrounding 'verifyVectrReleaseHelper' in vectr-install.log.  vectr-install.log should be in the same folder as the installer files.  The log entries will look like this:
```bash
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > printStatusMark FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < printStatusMark FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > verifyVectrReleaseHelper FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > verifyVectrRelease FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < verifyVectrRelease FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < verifyVectrReleaseHelper FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > printStatusMark FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < printStatusMark FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > dirExists FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [INFO]  Directory /home/vectruser/deploydirectory/app/config does not exist on disk
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < dirExists FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > verifyVectrReleaseHelper FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > verifyVectrRelease FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [ERROR]  VECTR temp extract dir /home/vectruser/deploydirectory/app/backup folder does not exist.
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  < verifyVectrReleaseHelper FUNCEXIT
[Wed Jul 17 10:42:01 EDT 2019] [DEBUG]  > copyFilesToFolder FUNCENTRY
[Wed Jul 17 10:42:01 EDT 2019] [INFO]  Copying files from download_temp/sra-vectr-runtime-5.2.0-ce to /home/vectruser/deploydirectory/app
```

**Comment by qq854051086** [comment]
It's my problem, because the zip here is decompressed manually and there are some errors caused by missing some folders. Now it's installed, but there's a new problem. When I click on login, HTML tells me 404
look it 
![20190723105806](https://user-images.githubusercontent.com/38556416/61679906-55c20d80-ad3a-11e9-85f0-cd4b87c6fa5d.png)

**Comment by thebleucheese** [comment]
There are a couple configuration files that are modified by the installer scripts 
**{DEPLOY_DIR}/app/config/auth.properties**
Verify that it shows something like 
```
cas.server.url=https://YOUR_VECTR_HOSTNAME:8443/cas'
```

**{DEPLOY_DIR}/app/cas/config/cas.properties**
Verify that it shows lines similar to 
```
cas.server.name=https://YOUR_VECTR_HOSTNAME:8443
cas.server.prefix=https://YOUR_VECTR_HOSTNAME:8443/cas
```
**{DEPLOY_DIR}/app/cas/services/*.json**
Verify a line similar to 
```
"serviceId" : "https://YOUR_VECTR_HOSTNAME:8081/sra-purpletools-webui/app\\?client_name=CasClient",
```

Did the installer script run successfully?  If you're using a ubuntu, mint, or centOS host it should perform all of these modifications for you based on what you enter in the install questions.

There's a cas.war file in the wars folder that gets extracted.  That should automatically be copied over and started by tomcat and if that's not happening something went wrong with the install process.

**Comment by qq854051086** [comment]
Yes, the installer has been successfully executed, and all of the above configurations are OK. I have done installation tests on CentOS and ubunto, all of which are the same 404.
This is my wars folder
![image](https://user-images.githubusercontent.com/38556416/61838442-d78d7480-aebb-11e9-9474-0bf0b343cb0d.png)

**Comment by thebleucheese** [comment]
Are you using the latest version - 5.2.2?  There are some *.war files missing and I wonder if that's due to the use of an older version.

I think the first thing we should do is try to find why there are missing *.war files

Your wars directory should like this before deploying:
```bash
root@144 ~/sra2/app/wars $ ls 
cas.war  sra-auth-rest.war         sra-purpletools-webui.war
ROOT     sra-purpletools-rest.war
```

And after deploying VECTR, the docker container should expand each of those wars into its own folder, like this:
```bash
root@144 ~/sra2/app/wars $ ls 
cas      sra-auth-rest         sra-purpletools-rest.war
cas.war  sra-auth-rest.war     sra-purpletools-webui
ROOT     sra-purpletools-rest  sra-purpletools-webui.war
```

**Comment by thebleucheese** [comment]
Also FYI, there is a video guide for the installation process here:

https://www.youtube.com/watch?v=SU6ZFwVyx7E

**Comment by qq854051086** [comment]
Thank you very much for your help. Now the project is available. It's really a zip file problem. download it manually and reinstall it after importing it.

**Comment by thebleucheese** [comment]
I should have realized this stated during the github outage, we encountered issues with dependency downloads around that time.  Thanks for sticking with it and getting it installed.
