### ISSUE TITLE
Functionnality Regression - Not able anymore to have multiple fields Metadata (Red Team)

### ISSUE THREAD

**Issue by L3houx** [SecurityRiskAdvisors/VECTR#230]
**Describe the bug**
The latest update of Vectr disables the functionality of having multiple Metadata fields in the Red Team section.

We used to use multiple metadata fields to have more details of the test case (sophistication, detection tool, etc.).

**To Reproduce**
- Select an assessment
- Select a campaign
- Select a test case
- Click on the "properties" button (section Red Team)
![image](https://user-images.githubusercontent.com/32520954/232864050-55c9ca5c-3ed1-46ea-a8a4-20a6d927b43f.png)

**Expected behavior**
Used to have multiple fields of metadata

**Screenshots**
Now: 
![image](https://user-images.githubusercontent.com/32520954/232864398-47f6a57e-d52f-4388-8132-e5d3c494f412.png)

Before: 
![image](https://user-images.githubusercontent.com/32520954/232864766-bfc1f32a-37a0-4841-966b-408b88662120.png)

**Additional context**
Our automated scripts didn't work anymore since we are not able to add multiple fields. We need an older version of Vectr to be able to have our automated process working.

**Comment by doodleincode** [comment]
Thanks for reporting this. Confirming that we're able to replicate the issue. We'll fix this in a future release.

In the mean time, there is a workaround that you can try. On the Campaign detail page, you can use the action menu to edit Red or Blue metadata.

![image](https://user-images.githubusercontent.com/1707777/232876920-91ca8da8-786e-41e3-bda7-1246d4e937ee.png)

**Comment by thebleucheese** [comment]
Fixed in prior VECTR version - noted multiple test case metadata fields working in 9.x+
