### ISSUE TITLE
Configuration Error - system time

### ISSUE THREAD

**Issue by kimberleyhallifax** [SecurityRiskAdvisors/VECTR#241]
**Describe the bug**

I'm running vectr on AWS Elastic Kubernetes Service in the `eu-west-1` zone (UTC). When I attempt to login, this is the response I get:

<img width="799" alt="Screen Shot 2023-07-24 at 11 52 27 am" src="https://github.com/SecurityRiskAdvisors/VECTR/assets/49122574/bce86f1f-4315-4497-bcaf-83818a8168f6">

I figured that all I needed to do was just to change the linux system times in each container to my time zone (AWST), so I did that, but I still get the same error with vectr in UTC time. Here's the evidence for my containers having AWST time:

<img width="1014" alt="Screen Shot 2023-07-24 at 11 58 22 am" src="https://github.com/SecurityRiskAdvisors/VECTR/assets/49122574/41206bc5-3558-48a5-afeb-5740bb2d28b0">

The commands I ran to change to AWST are:

```sh
rm -rf /etc/localtime
ln -s /usr/share/zoneinfo/Australia/Perth /etc/localtime
```

**To Reproduce**

Not possible unless you sign up to AWS.

**Expected behavior**

The usual login page.

**Desktop:**

 - OS: macOS Monterey M1
 - Browser: Chrome
 - Version: 114.0.5735.198

My browser time is AWST.

I'm just wondering if you guys know where this UTC time is still persisting and where I can go to update it?

**Comment by SRAPSpencer** [comment]
VECTR uses Epoch time,

https://www.epoch101.com/

Time zones aren't relevant, only the absolute time. Your browser machine is likely +/-30 seconds or more from the server time.

**Comment by kimberleyhallifax** [comment]
> https://www.epoch101.com/

Ah, thank you @SRAPSpencer. I can login through a different device :)

**Comment by nonsleepr** [comment]
> VECTR uses Epoch time,
> 
> https://www.epoch101.com/
> 
> Time zones aren't relevant, only the absolute time. Your browser machine is likely +/-30 seconds or more from the server time.

That's misleading, had the same issue but epoch101 shows my system time, not the actual time.
https://time.gov/ is a better way to check.
