### ISSUE TITLE
Docker Compose stuck on org.apache.catalina.startup.Catalina.start Server startup

### ISSUE THREAD

**Issue by kkamran1010** [SecurityRiskAdvisors/VECTR#243]
building out a Vectr instance, mongodb sits on a sperate instance. But can connect and create the required DBs fine on the separate instance and i can see them.

But docker compose runs and seems to get stuck on org.apache.catalina.startup.Catalina.start Server startup. I cannot access the web server either seems to be what is failing. I've uploaded the log to see the other errors and see if there is anything being seen that i cannot see. 

[docker compose.txt](https://github.com/SecurityRiskAdvisors/VECTR/files/12411215/docker.compose.txt)

**Comment by SRAPSpencer** [comment]
We don't offer community support for remote databases. Having said that this startup looks normal, your issue is likely unrelated to having a remote database. 

Do you have DNS configured to access the webserver front end?

**Comment by kkamran1010** [comment]
> We don't offer community support for remote databases. Having said that this startup looks normal, your issue is likely unrelated to having a remote database.
> 
> Do you have DNS configured to access the webserver front end?

yes, i have a DNS record in place. It just spins for many minutes then gives "ERR_EMPTY_RESPONSE" error.

**Comment by SRAPSpencer** [comment]
There's likely a networking issue between the docker network, the docker host and your client browser.

**Comment by kkamran1010** [comment]
> There's likely a networking issue between the docker network, the docker host and your client browser.
> 
> It's difficult to pinpoint since your docker logs you attached are normal. We would need to know more about the operating environment.

is it normal for it be stuck on org.apache.catalina.startup.Catalina.start after running docker compose up? ive had it deployed in dev and it worked normally but i dont remember it being stuck there. My dev instance runs into the same issue after i upgraded the version in the docker compose file. Dev uses Centos, prod i tried using Rocky. I can try ubuntu but i dont think the issue is related to OS unless something changed in the images and that would explain why when i upgraded version it crashed?

**Comment by SRAPSpencer** [comment]
> > There's likely a networking issue between the docker network, the docker host and your client browser.
> > It's difficult to pinpoint since your docker logs you attached are normal. We would need to know more about the operating environment.
> 
> is it normal for it be stuck on org.apache.catalina.startup.Catalina.start after running docker compose up? ive had it deployed in dev and it worked normally but i dont remember it being stuck there. My dev instance runs into the same issue after i upgraded the version in the docker compose file. Dev uses Centos, prod i tried using Rocky. I can try ubuntu but i dont think the issue is related to OS unless something changed in the images and that would explain why when i upgraded version it crashed?

The last line

`org.apache.catalina.startup.Catalina.start Server startup in [28114] milliseconds`

Is the end of the startup procedure for VECTR and expected. 

Using CentOS/Rocky/RHEL based OS's has many issues due to RHEL's disagreements with Docker and their own Podman platform. You're likely encountering a SE Linux or other Firewall issue with Docker being unable to open the ports required on those distros.

**Comment by kkamran1010** [comment]
> > > There's likely a networking issue between the docker network, the docker host and your client browser.
> > > It's difficult to pinpoint since your docker logs you attached are normal. We would need to know more about the operating environment.
> > 
> > 
> > is it normal for it be stuck on org.apache.catalina.startup.Catalina.start after running docker compose up? ive had it deployed in dev and it worked normally but i dont remember it being stuck there. My dev instance runs into the same issue after i upgraded the version in the docker compose file. Dev uses Centos, prod i tried using Rocky. I can try ubuntu but i dont think the issue is related to OS unless something changed in the images and that would explain why when i upgraded version it crashed?
> 
> The last line
> 
> `org.apache.catalina.startup.Catalina.start Server startup in [28114] milliseconds`
> 
> Is the end of the startup procedure for VECTR and expected.
> 
> Using CentOS/Rocky/RHEL based OS's has many issues due to RHEL's disagreements with Docker and their own Podman platform. You're likely encountering a SE Linux or other Firewall issue with Docker being unable to open the ports required on those distros.

but it is supposed to end right? not hang? i do not recall having to create a new sessions after running docker compose up is why i ask.

i turned off SE Linux, no firewall. 

i see below when running netstat for port 8081. 

 netstat -na | grep 8081
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN
tcp6       0      0 :::8081                 :::*                    LISTEN

should 8081 be listening on the IP of the server?

**Comment by SRAPSpencer** [comment]
If you're running 

`docker compose up -d`

It will run in deamon mode. Meaning the containers will run in the background. If you're running it without the -d when you kill the terminal session it will stop the containers. 

Nothing else will enter the log until an attempted login is made or other activity on the server.

**Comment by kkamran1010** [comment]
this can be closed, was a new firewall rule blocking 8081 causing my issues! working as expected now.
