### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by z00f** [SecurityRiskAdvisors/VECTR#246]
Hi.
There is a problem with the correct time of the containers after running 
docker compose up -d

Configuration error
VECTR system time and local browser time are not in-sync. The difference in time was greater than the allowable range.

Error code: 102

Is there any way to fix it? I can not log on.
Thanks.
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/34635749/78eaa847-039d-407b-bea3-bd2941d27dbf)

**Comment by SRAPSpencer** [comment]
See this issue, 

https://github.com/SecurityRiskAdvisors/VECTR/issues/241

Check the time difference between your docker host and your client browser. Even 10-15 seconds can create this error as it breaks auth.

**Comment by thebleucheese** [comment]
Closing as known configuration issue - time server drift. Needs to be fixed in deployment environment.
