### ISSUE TITLE
Add atomics tests prerequisite commands in vect test cases

### ISSUE THREAD

**Issue by ilovax** [SecurityRiskAdvisors/VECTR#248]
Hello,
I noticed while developing test cases in vect that the ATR test cases usually use `get prerequisite` commands which i couldn't find a way to do automatically. I would like to suggest to add such feature that extracts the commands from the index.yaml the same way it does in the `primary commands` and `cleanup commands`

**Comment by SRAPSpencer** [comment]
We already have an open feature request for this, 

https://github.com/SecurityRiskAdvisors/VECTR/issues/218

Feel free to add any thoughts there.
