### ISSUE TITLE
Bug: Assessment Report is Missing Test Cases

### ISSUE THREAD

**Issue by joebloggs12** [SecurityRiskAdvisors/VECTR#256]
**Describe the bug**
If you create an assessment with a single campaign, with a few test cases, although these test cases show up in the campaign screen and other reports, if you create an Assessment-level report, test cases can be missing.

**To Reproduce**
1. Create a new environment
2. Create a new assessment
3. Create a new campaign
4. Create 4 test cases
5. Go back to Assessments screen and download a Detailed Campaign Report.
6. You should see a missing Test Case.

**Expected behavior**
All created test cases should exist in the Detailed Campaign Report.

**Screenshots**
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/108157390/92a3738f-5318-4c1a-9384-c228a6d58353)
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/108157390/e340e51e-5777-43e2-86cc-e4dc8b8a66bb)
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/108157390/5013a58d-dab3-4e95-98db-7578bc7654eb)
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/108157390/c4e47a1f-a2d7-4b05-9be6-dbd07a3c0a29)

**User Platform(please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 121.0.2277.98 (Official build) (64-bit)

**VECTR Host(please complete the following information):**
 - Linux Distro: Ubuntu
 - Linux Version: 22.04.3 LTS
 - VECTR Version: 8.9.3

**Additional context**
Test cases do exist when whole database is exported, but just not in the above report.

**Comment by SRAPSpencer** [comment]
Thanks for the report, we'll look into this and address in a future release.

**Comment by joebloggs12** [comment]
I've found out a little more about this. The above screenshot was from WordPad, but when copied over to a different system and opened up in Word, all entries show as normal. Not sure why the discrepancy, but looks like a possible issue in WordPad instead of the VECTR export.

**Comment by thebleucheese** [comment]
closing as external application issue
