### ISSUE TITLE
Importing an ATTiRe log file via GraphQL API

### ISSUE THREAD

**Issue by ApeironDragon** [SecurityRiskAdvisors/VECTR#259]
**Describe the topic**
Hello, I have a report generated from Caldera, I used the CalderaToAttire project to convert it into an ATTiRe log file, and now I want to import it into Vectr using API but I am still new to this so I don't have a good idea on how to do so. If someone can please walk me through that I would greatly appreciate it. Thank you!

**Comment by SRAPSpencer** [comment]
You can follow the steps from the ATTiRe repo to import converted files. 

https://github.com/SecurityRiskAdvisors/ATTiRe

**Comment by ApeironDragon** [comment]
I need to do it via API though for a project I'm working on.

**Comment by SRAPSpencer** [comment]
You can find the GraphQL documentation for test cases here, 

https://docs.vectr.io/graphql/schema/testcase.doc.html

Also we have an example API project here, 

https://github.com/SecurityRiskAdvisors/vectr-tools

I would recommend starting there, if you have a specific issue with a query you're troubleshooting feel free to open an issue for that or ask in our Discord.

Helping build something from scratch is outside of the scope of community support. If you'd like a formal business support engagement feel free to reach out here,

https://vectr.io/contact/
