### ISSUE TITLE
Feature: Sort Campaign Templates Alphabetically

### ISSUE THREAD

**Issue by tamenzel** [SecurityRiskAdvisors/VECTR#262]
When adding a campaign, the list of templates is 
extremely long.  It would be very helpful if the list was sorted alphabetically to be able to find the threat actor group that you are interested in.  Typing in the name of the group is not as helpful as it sounds.  Example: typing in "Bronze Silhouette" starts to bring up "BRONZE BUTLER" but when you hit the first "e" it then changes to Elise.  This is on version 8.9.4 

On 9.0.2, it is even less helpful to start typing in the name.  The name changes on every letter B=BS2005, r=RawPOS, o=OceanSalt.  This would be ok if you then went to the list and you were in the start of that letter but it takes you to the template in a non sorted list.  
![Screenshot 2024-04-19 at 12 57 19 PM](https://github.com/SecurityRiskAdvisors/VECTR/assets/48569964/3f08ffdd-5d8a-4d0e-bb14-70440eca1973)
![Screenshot 2024-04-19 at 1 02 29 PM](https://github.com/SecurityRiskAdvisors/VECTR/assets/48569964/65daa629-2482-4bab-b5ef-e9f4c7ec4390)

**Comment by tamenzel** [comment]
![Screenshot 2024-04-19 at 12 57 58 PM](https://github.com/SecurityRiskAdvisors/VECTR/assets/48569964/d9a151ed-d2c8-4f7b-89f5-64099056be82)

**Comment by SRAPSpencer** [comment]
Thanks for the feedback. This is one of our legacy UI elements which will be replaced in the coming months. I'll make sure your feedback gets to the team when they pick this one up for a re-work.

**Comment by tamenzel** [comment]
Thanks for the quick response.  It really is a great piece of software to work with and I know all of us that do Purple Teaming thank SRA for it.

**Comment by doodleincode** [comment]
This has been fixed in [9.2.1](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-9.2.1).
