### ISSUE TITLE
Bug: Defining an empty variable creates a duplicate error

### ISSUE THREAD

**Issue by dsolstad** [SecurityRiskAdvisors/VECTR#267]
Test case won't build because there is an empty variable:
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/346888/8183f012-3a33-43b0-a9f8-defbf5e8cd3b)

Setting a variable creates this error:
![image](https://github.com/SecurityRiskAdvisors/VECTR/assets/346888/9ccbba9c-ab7d-490b-bc35-42af71fc57fe)

Removing the variable only makes it reappear empty again.

**Comment by doodleincode** [comment]
Thanks for reporting this.

We are aware of the issue and should have a fix for it soon.
