### ISSUE TITLE
Feature: Postgres host variable getting overwritten

### ISSUE THREAD

**Issue by kkamran1010** [SecurityRiskAdvisors/VECTR#268]
**Is your feature request related to a problem? Please describe.**
the postgres host variable is getting overwritten. if i look into the docker tomcat container, under the conf folder the server xml has the jdbc string correct. but if i review the catalina log or the log/localhost log both show the wrong string and the connection does not work.  it keeps the default variable and adds the variable from the .env after the default one. example below.

log shows jdbc:postgresql://vectr-postgres:5432/(POSTGRES_HOST= variable from .env)/vectr

but in server.xml file it shows jdbc:postgresql://(POSTGRES_HOST= variable from .env)/vectr

i cannot find where its getting overwritten from, but seems like a possible bug as well.

**Describe the solution you'd like**
a way for the variable to work and not get overwritten by the default variable from the image. 

**Describe alternatives you've considered**
we have a work around-ish that works but not great, we modified the environment files so post-gres points to the postgres host we want to use. 

**Additional context**
understood remote db is not supported, but i still believe it is a bug.

**Comment by doodleincode** [comment]
This has been fixed in [9.2.1](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-9.2.1).
