### ISSUE TITLE
General Assistance: How to upgrade Vectr while preserving data?

### ISSUE THREAD

**Issue by dsolstad** [SecurityRiskAdvisors/VECTR#274]
I want to upgrade to the newest version of Vectr, but not sure if this will delete the data from my previous campaigns. Will updating the docker compose file to the newest images preserve my existing data?

**Comment by mkalkanli** [comment]
25 Haz 2024 Sal, saat 10:46 tarihinde Daniel Solstad <
***@***.***> şunu yazdı:

**Comment by dsolstad** [comment]
Thanks!
