### ISSUE TITLE
Bug: Vanilla Docker container Images with scripts errors | Error create environment

### ISSUE THREAD

**Issue by L3houx** [SecurityRiskAdvisors/VECTR#283]
**Describe the bug**
I tried a brand new vanilla version of Vectr and I tried to create a new environment but I had errors creating it. I also tried different versions of Vectr 9.X (9.0.2 ; 9.2.1; 9.3.3) and I got the same problem on every version.

**To Reproduce**
1. docker compose new instance
2. Connect to the new instance using the default credentials
3. Click on ' Select Active Environment'
4. Click on the plus sign '+'
5. Enter the name of a new environment without spaces
6. Click on check mark '✅'
7. Check the network message and get an error

```
SQL [insert into "vectr"."env_defense_tool" ("name", "description", "active", "environment_id", "cl_defense_tool_id", "cl_defense_tool_product_id") select "vectr"."cl_defense_tool"."name", "vectr"."cl_defense_tool"."description", ? as "active", ? as "environment_id", "vectr"."cl_defense_tool"."id", "vectr"."cl_defense_tool"."cl_defense_tool_product_id" from "vectr"."cl_defense_tool" where "vectr"."cl_defense_tool"."active" = ?]; ERROR: column cl_defense_tool.active does not exist  Hint: Perhaps you meant to reference the column "env_defense_tool.active".  Position: 390
```

**Expected behavior**
Be able to create a new environment

**Screenshots**

Docker containers are running

![image](https://github.com/user-attachments/assets/cb06209a-c1f0-49ef-a70c-beb9c4e9b0b8)

Create new environment

![image](https://github.com/user-attachments/assets/9b018823-060b-4a16-af72-dffe6c6a9f5f)

![image](https://github.com/user-attachments/assets/f9b5ba61-b982-46be-9eb7-a5eba7281310)

**User Platform(please complete the following information):**
 - OS: Linux Ubuntu 22.04.4
 - Browser Firefox
 - Version 129.0.2

**VECTR Host(please complete the following information):**
 - Linux Distro: Linux Ubuntu 
 - Linux Version: 22.04.4
 - VECTR Version 9.2.1
- Docker Version 27.1.1, build 6312585

**Comment by SRAPSpencer** [comment]
Thanks for reporting, we're trying to replicate this internally. We'll let you know if we need any additional information.

**Comment by thebleucheese** [comment]
We're currently unable to reproduce this with any 9.x+ VECTR version. The error you're receiving states that a column doesn't exist (cl_defense_tool.active) which should always be present in VECTR. It's included in the default data set and is a baseline migration. 

We'll do some more investigation into the queries used to copy data in case the error is misleading, but it looks like there's possible data corruption of the SQL schema. Are you seeing any other issues or errors on startup?

**Comment by L3houx** [comment]
I deleted the instance and forced the rebuild and everything worked fine after that rebuild. After having more and more problems all over the instance, I decided to rebuild one. Sorry for the delay, we can close the issue.
