### ISSUE TITLE
Question - Template Creation and Portability

### ISSUE THREAD

**Issue by SRAPSpencer** [SecurityRiskAdvisors/VECTR#286]
Hi @SRAPSpencer,

I have another question regarding this suggestion of yours:

> If you are trying to export templates, you need to create them as templates before you can export them.

Did I understand correctly, that creating a test case as template works via `Library -> Test Case Library -> New Test Case` (and the same procedure works for campaigns and assessments)?

If so, how do I export those templates after creating them? I don't seem to be able to find the functionality in the GUI so is this only possible via the API? Are there examples for this available?
I assume that the import then simply works via the `Import Data` GUI-functionality?

Context:
I have multiple Vectr installations and want to be able to share "empty"/template test cases/campaigns/assessments between them without having to manually re create them over and over...

_Originally posted by @FabFaeb in https://github.com/SecurityRiskAdvisors/VECTR/issues/244#issuecomment-2382779696_

**Comment by FabFaeb** [comment]
Thanks for the quick reply, that seems to work!
