### ISSUE TITLE
No indicator as to when an evidence file is uploaded to a test case

### ISSUE THREAD

**Issue by punchdrunktux** [SecurityRiskAdvisors/VECTR#29]
When you attach an screenshot/image file to a test case, if you immediately click "save" many times the file fails to attach as evidence.  It appears that the test case dialogue must be left open for some time to allow the file to be uploaded in the background.  However, it's difficult to know when the upload has completed, as there are no visual indicators or messages. 

Adding a visual queue as to when the file has been successfully attached or, even better, attaching the file in the background without the need to leave the test case dialogue open would enhance the experience.

**Comment by carlvonderheid** [comment]
Yes, thanks for the feedback!  We will add this to the next release.

**Comment by carlvonderheid** [comment]
We added an evidence file upload indicator that will show your progress in the 5.3.0 release.
