### ISSUE TITLE
Feature: RBAC Policies/Options to only Allow Editing of "Blue side"

### ISSUE THREAD

**Issue by The1ntern** [SecurityRiskAdvisors/VECTR#293]
**Is your feature request related to a problem? Please describe.**

In the event we want to provide a customer temporary access to VECTR to input results from the "blue perspective" for test cases they have the ability to edit the "red side" of the test case. While both parties accessing the system should be trusted I think this allows a user to have more write access then necessary. 

**Describe the solution you'd like**

The creation of a new policy which can be added to groups which allows "read" access into the "red side" of the test case but allows "write" access to the "blue side" of the test case. This would continue to facilitate collaboration between teams but prevent modifications to the red teams notes. 

**Describe alternatives you've considered**

Can not think of an alternative at the moment since I believe the most restrictive you can be is based on "environment". Once a user has permission to access an environment they have access to everything underlying within. 

**Additional context**

Do not have any screenshots at the moment but can add if requested.

**Comment by SRAPSpencer** [comment]
@The1ntern Thanks for submitting this feature request. Two things, 

1. I'm not sure what organization you work for, but we do have a licensing program for consulting organizations to use VECTR. Should your organization be a member I would consult your team as we have channels for feature requests from those organizations. If you are not I would advise you to refer to the EULA for the terms of use, https://github.com/SecurityRiskAdvisors/VECTR/blob/master/VECTR%20End%20User%20License%20Agreement.pdf
2. This sounds like a dupe of https://github.com/SecurityRiskAdvisors/VECTR/issues/97 Feel free to correct me if you have a different take on it. We have not implemented thus far as we believe Purple Teaming is a truly collaborative process and this is a low value add for our workflows. We haven't ruled out adding it in the future.

**Comment by The1ntern** [comment]
Thanks for the response @SRAPSpencer! Appreciate the resources you sent over. This does appear to be a duplicate of https://github.com/SecurityRiskAdvisors/VECTR/issues/97 my apologies.
