### ISSUE TITLE
Unable to attach analysis rules to default detection rule mappings

### ISSUE THREAD

**Issue by rhaddock14** [SecurityRiskAdvisors/VECTR#30]
The ability to add an analysis rule to a default detection rule mapping (behavior) is not present. The screen & option is there but the checkbox is disabled.

When a new behavior is created, the ability to attach an analysis rule works correctly. Feature request is to extend this functionality to the default behaviors.

**Comment by carlvonderheid** [comment]
This was actually a bug.  Fixed in 5.3.0 release.
