### ISSUE TITLE
Login Fail - Invalid Service Ticket

### ISSUE THREAD

**Issue by antman1p** [SecurityRiskAdvisors/VECTR#35]
On VMWare Fusion
Ubuntu 64 bit 18.04.2
Docker 19.03.5, build 633a0ea838
docker-compose version 1.24.1, build 4667896b
Vectr Release Package ce-5.3.1 - MITRE October 2019 Integration

Logging in for the first time to the web interface at localhost:8081 gives me "Invalid service ticket. It was either unrecognized or has expired."

I know the credentials are correct, because if I use the wrong password I get a different response.
![vectrFailScrnsht](https://user-images.githubusercontent.com/6889529/68901008-b070e200-06fa-11ea-80a3-1e8a1617fb9f.png)

**Comment by carlvonderheid** [comment]
Did you use the installation scripts?  For the hostname, did you enter localhost or 127.0.0.1?

**Comment by antman1p** [comment]
For the hostname i entered "localhost."  I downloaded the latest release zip and ran docker-compose.  I did not do any running of any othjer scripts.  Is there a step in the instructions for running scripts that I missed?

**Comment by carlvonderheid** [comment]
I think there is a step you missed, but assuming you're running on localhost, then you can probably get away with doing the following:

1.  from the /opt/vectr/config directory, run:
sudo openssl req -x509 -new -nodes -config selfSigned.conf -keyout ssl.key -out ssl.crt

if this command fails, it's possible that there are 2 directories named ssl.key and ssl.crt under the /opt/vectr/config directory.  Remove those directories and run again.

2.  Stop the containers that are running.  Whichever command you did to start/run the containers, do the same with a stop at the end.  So for example, if you did "sudo docker-compose up", run "sudo docker-compose down".  Do this from the /opt/vectr directory.

3.  Start the containers like this (from the /opt/vectr dir):
sudo docker-compose -f docker-compose.yml -f devSsl.yml -p dev up -d

You can find more complete documentation here:
https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation#vectr-installation-instructions

Or a video installation guide here:
https://github.com/SecurityRiskAdvisors/VECTR/wiki/How-To-Videos (Click the VECTR Ubuntu Installation)

**Comment by antman1p** [comment]
I performed that step and it did not fail, yet I am having this issue.  I decided to start over with a fresh VM and clone the github repo instead of using the release zip, and followed the installation instructions.  I navigated to the default url.  Everyhting worked this way.  I'm not sure why the release doesn't work, but I will just stick wiht this method.  Next I need to put it up into aws to demo to my team.  Are there instructions for changing the config file so this works with a domain I register and link to my AWS public addr, seeing how I can't just use the public IP to navigate to?

**Comment by carlvonderheid** [comment]
Can you email VECTR@securityriskadvisors.com with a contact email address and we can discuss further?

**Comment by swtornio** [comment]
I just used the docker install on ubuntu with the current release and get this same error. I would rather not start over with a manual installation since this is a demo/test installation and I'd just like to get it working for evaluation. Is there a configuration item that needs to be changed?

**Comment by SRAPSpencer** [comment]
@swtornio How are you navigating to the instance? If you're using localhost like pictured above or anything other than the host-name specified in the installer you will receive that error. If you left the defaults in place that would likely be sravectr.internal
![image](https://user-images.githubusercontent.com/57723275/74350870-5d9fd880-4d84-11ea-9ca5-253dc70a698f.png)
Navigating to the instance via the hostname you specified or rerunning the installer to match the host name of your choice should resolve the issue.

**Comment by swtornio** [comment]
I am using the docker release, and did not run an installer. The docker instructions don't appear to reference it, or I missed it. 

I am accessing the instance using https://localhost:8081. If I create a hosts entry for sravectr,internal, and hit https://sravectr.internal:8081, I get an "Application Not Authorized to Use CAS" error. Using localhost allows me to submit a login without the CAS error, but then redirects me to the login page and gives the "Invalid service ticket. It was either unrecognized or has expired." error

**Comment by SRAPSpencer** [comment]
I would recommend using the wiki instructions. https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation

If you followed the Linux Docker(Manual) on the main page then you'll want to do a docker-compose down or cleanup your current containers however you see fit. 

Start at the Ubuntu dependency page and follow from there,
