### ISSUE TITLE
Cannot save added events in timeline

### ISSUE THREAD

**Issue by korgull** [SecurityRiskAdvisors/VECTR#4]
When adding events into the timeline using the "+" symbol on the bottom left of the timeline, I do get an indication that the event was added (type blue, red, or neutral).  However, the only way to exit the screen where you add events is to hit the "x" at the top right of the dialog box.  Doing that removes the event from the timeline (top left says "Cancelled").

**Comment by thebleucheese** [comment]
Hey, Thanks for the issue reports.  You're correct about them not saving.  I'm assuming you're talking about adding them to a test case when you click on one of the cog buttons in each of the timeline panels.  They only save if you click the new event after you've added it as a start/stop event.  Then they get attached to the test case.  We'll try to see if there's a cleaner way to interact with timeline events and save them from that dialog.

**Comment by korgull** [comment]
Hi,
Thanks for the quick reply.  Here is a screenshot of the situation, which I think you describe.  This is a great way to note when White team (could annotate with “neutral”) intervenes. I’m still exploring, but I didn’t see another way to note actions taken by other teams.

**Comment by carlvonderheid** [comment]
Fixed on tag ce-4.4.0
