### ISSUE TITLE
vectr source code

### ISSUE THREAD

**Issue by alowenstein** [SecurityRiskAdvisors/VECTR#40]
Hi, 
not really an issue but a question - 
We're looking into the possibility of making proprietary changes to vectr that will fit our business needs but the source code is not available. 
Is there a way to obtain it?

Thank you.

**Comment by carlvonderheid** [comment]
We are currently keeping the project closed source.  Feel free to email us at vectr@securityriskadvisors.com if you'd like to set up a separate email thread to discuss possible solutions to your business needs.  Thanks!

**Comment by initstring** [comment]
I realize this is a closed issue, but I hear that there are plans to open source. If that is accurate, would it be possible to re-open this issue or open another so that I can follow the progress?
Thanks!
