### ISSUE TITLE
Details modal in heatmap doesn't work in FireFox. 

### ISSUE THREAD

**Issue by alowenstein** [SecurityRiskAdvisors/VECTR#43]
Hi, 

in reporting -> report type=heatmap -> clicking any one of the cells that has a color in it. 
In Chrome (79.0.3945.117), a details modal appears but in FF (71) it doesn't. 

Thanks.

**Comment by alowenstein** [comment]
Same for tooltips - they appear in Chrome but not in FF.

**Comment by carlvonderheid** [comment]
Should be fixed in 5.5.6
