### ISSUE TITLE
data discrepancies between test case drill down and heat map report

### ISSUE THREAD

**Issue by alowenstein** [SecurityRiskAdvisors/VECTR#44]
Hi, 

I the drill down report, I have 3 test cases, all mapped to a MITRE ID, all completed with blocked outcome. 
When I switch to Heat map, there are only 2.
Let me know what additional details you need.

Thanks.

**Comment by carlvonderheid** [comment]
This was solved offline.  The issue was the MapType and DisplayMode in the Heat Map were set to not allow all data to show.
