### ISSUE TITLE
How can I see the "automation" made by Red Team

### ISSUE THREAD

**Issue by radiusmk** [SecurityRiskAdvisors/VECTR#48]
In "Test case" list, inside a campaing, some itens show a icon with the description: "Red Team Automation Availble". Can I see this automation? How can I add a automation to a Test Case?

Thanks.

**Comment by thebleucheese** [comment]
We're currently in development with an endpoint automation feature.  That's our mistake for not hiding that icon.  

Based on progress we expect about a month more development and then we'll begin testing and verifying for quality before we release.
