### ISSUE TITLE
Restrict access to mongodb

### ISSUE THREAD

**Issue by radiusmk** [SecurityRiskAdvisors/VECTR#49]
Is it possible set a password to Vectr access MondoDB database? In "vectr.properties" file there are only host and port sets.

What is the recommendation to restric access to databases without cause problems to Vectr?

About backup, there is a way to schedule tasks on Vectr? I used the backup option on GUI and works fine, but I did't locate a option to schedule.

Thanks.
Marco Aurélio

**Comment by thebleucheese** [comment]
Hi Marco,
We're currently looking into passwording the MongoDB database. It requires some code changes in the back-end that we're investigating. The hope was to get it into the next upcoming release (5.4.0), but we hit a weird snag with some of our dependencies so we have to modify not just our code, but vendor code as well. For that reason, it won't make the next release. We don't have an exact ETA on this, but we hope to resolve it soon.  

In our environments, we block access to MongoDB at the infrastructure level - the easiest way to do this is by removing the port sharing for the mongo container in the devSsl.yml file. That way, mongo is only exposed internally inside the docker network. 

You should see something like the following in devSsl.yml:
`


    services:

    mongo:

    ports:

      - "27208:27017"

    container_name: sravectr_mongo

    volumes:

      - /home/vectruser/sravectr/data:/data/db`

From here you can remove the line with "ports:" and the following like that says ' - "27208:27017"' and this will make the db container accessible solely to the internal docker network.

We don't have any built-in methods to automate backups right now, but there are a lot of different ways to accomplish that goal at the docker host level.  You can setup a cron to run mongodump against the vectr-mongo container inside the vectr-tomcat container.  You could add a new docker volume in docker-compose.yml.  The tomcat cron could be built as shell commands into the DOCKERFILE or you could have it mount and execute a script.  More cumbersome, but possibly easier to manage from a host perspective you could write a script that stops the containers and backs up VECTR's "data" folder.  This contains the full contents of the Mongo database.

**Comment by radiusmk** [comment]
Ok, thanks.
