### ISSUE TITLE
Deletion of analysis rules

### ISSUE THREAD

**Issue by rowi9631** [SecurityRiskAdvisors/VECTR#53]
Trying to delete analysis rules, and there doesn't seem to be an option to delete analysis engine rules.

**Comment by carlvonderheid** [comment]
Sorry for the delay in responding to this.  We are doing a fairly large revamp of how we are handling detection rules in the system and will be released later this year.  This will be fixed in that release.

**Comment by carlvonderheid** [comment]
Fixed in 8.2.0
