### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by DorjM** [SecurityRiskAdvisors/VECTR#55]
Hi,

To start docker , its showing below error.

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file form

**Comment by carlvonderheid** [comment]
Hi, I think your docker-compose or docker engine is out of date.  Our docker-compose.yml file is specifying version 3.  

Here is the Docker engine compatibility matrix (you'll need at least 1.13.0)
[https://docs.docker.com/compose/compose-file/](https://docs.docker.com/compose/compose-file/)

Looks like version 3 is supported in docker-compose > 1.10.0:
"Compose file format 3.0 was first introduced in Compose release 1.10.0"

Documentation on installing docker-compose here: 
[https://docs.docker.com/compose/install/](https://docs.docker.com/compose/install/)

Documentation on installing docker engine here:
[https://docs.docker.com/install/](https://docs.docker.com/install/)

We also provide instructions on our wiki:
[https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation---Ubuntu](https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation---Ubuntu)
[https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation---Linux-Mint](https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation---Linux-Mint)
[https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation-CentOS](https://github.com/SecurityRiskAdvisors/VECTR/wiki/Installation-CentOS)
