### ISSUE TITLE
Import Test Case(s) from a file

### ISSUE THREAD

**Issue by getshellz** [SecurityRiskAdvisors/VECTR#59]
Would be great to have the ability to import a case from a file such as xml/json. It would allow flexibility to write scripts/tools that would execute certain TTPs and then create the associated test case(s) files that can then be imported into Vectr to allow a level of automation/ease for recording details.

**Comment by SRAPSpencer** [comment]
We currently have features that would meet these requirements on the roadmap but we have no ETA on delivery.

**Comment by ndubss** [comment]
+1 this would be useful

**Comment by carlvonderheid** [comment]
This is released in 8.2.0.  Also see the CSV import tool available here:

https://github.com/SecurityRiskAdvisors/vectr-tools#graphql-api-sample---csv-import
