### ISSUE TITLE
User Access Management

### ISSUE THREAD

**Issue by SolAngelus** [SecurityRiskAdvisors/VECTR#63]
I've begun creating accounts for team members and found that the user role has the same or very similar to the admin role.

Is there any documentation currently available that shows the differences between the two roles?

Is there any controls that I am missing either in the web gui or server side that would allow a admin to tweak these roles?

If not, is this something that is planned for the future?

**Comment by thebleucheese** [comment]
Currently, there are only 3 roles:

- Admin
- User
- Read-only

Admin/user are pretty similar, but the normal User role can't perform user management.  Read-only can't write data to the system and is just meant to view reports.

There are plans in our development roadmap for much more detailed access control following some general AuthN/AuthZ improvements that are needed to support those features.

**Comment by SolAngelus** [comment]
Thanks for the insight. Closing.
