### ISSUE TITLE
HTTP400 Error when updating test case

### ISSUE THREAD

**Issue by haroldddd** [SecurityRiskAdvisors/VECTR#66]
In the Campaign templates tab, whenever I try to update an existing Test-Case template, I observed the return of the following HTTP 400 error :

```
{"message":"Unable to update test case. Invalid icon file.","description":null}
``` 
It happens no matter what is typed in the forms, which makes it completely impossible (from what I saw) to edit a test-case template.

The error seems to come from the default test-case icon resource, which returns a 404 : `/static/icons/T1159.svg`

**Comment by thebleucheese** [comment]
Are you on version 5.5.9? 5.5.8 had an issue when updating from a prior version. 5.5.9 should fix it (you can just change the version in the docker-compose file)
