### ISSUE TITLE
Vectr Active Directory support

### ISSUE THREAD

**Issue by ab-ha-y** [SecurityRiskAdvisors/VECTR#68]
Hi Vectr team,

I wanted to know if the vectr has AD support. If not, do you have a plan to support it in the future?

Thanks!

**Comment by thebleucheese** [comment]
Do you mean ADFS support for single sign-on?

If so, the current release doesn't have it, but we're in the process of testing support for SSO (SAML and OpenID Connect only initially, which will include support for Azure AD). Development is done for it. It's expected to be delivered in the next major release.

Shortly after that is delivered we plan on adding support for MFA for local accounts.

**Comment by abby31** [comment]
Thanks for the update, hope to see the release soon!

**Comment by doodleincode** [comment]
Support for SSO integration with OIDC and SAML2 has been added in [8.0.0](https://github.com/SecurityRiskAdvisors/VECTR/releases/tag/ce-8.0.0). View the docs here: https://docs.vectr.io/sso/

Note, we've seen some instances where you might need to hard refresh your browser (`Ctrl+F5` or `Ctrl+Shift+R`) to see some of the newly enabled features.
