### ISSUE TITLE
tomcat container restarting / Running in Azure

### ISSUE THREAD

**Issue by neil-fox** [SecurityRiskAdvisors/VECTR#79]
Hi,

I have attempted to install vectr on Ubuntu 18.04, this has been done in Azure and the install appears to be successful (no error messages).

I have two questions.

1. After installing vectr my tomcat container is constantly restarting, how do I resolve this as i cant access the web gui?
![image](https://user-images.githubusercontent.com/26876090/88897810-ca7c3180-d243-11ea-9187-e774c4d46f63.png)

2. As this has been setup in azure what do i need to configure to access the web portal once the tomcat issue has been resolved? The Ubuntu box has an internal and external IP, obviously I wont be on the same internal subnet so any guidance would be appreciated.

This is my 3rd attempt of trying to setup vectr so any help would be greatly appreciated.

Thanks

Neil

**Comment by carlvonderheid** [comment]
Hi Neil. The restarting occurs if the container stops without a user specifically stopping it with a command.  We would need to see your logs to point you in the right direction.  We can take a look if you send them to:

vectrops@securityriskadvisors.com

The latter is a slightly more difficult question to answer without knowing the specifics of your environment.  Your EC2 will have a port that is listening (VECTR_PORT in your .env, 8081 by default) which gets forwarded to the Tomcat container.  How you access that port on your EC2 is environment specific.  You can do something comprehensive like setting up a Load Balancer, or you can do something very quick like setting up a Security Group and opening up that port to an IP range.

**Comment by neil-fox** [comment]
Hi Carl,

Thanks for the response, if you can provide the location of the logs I will send them over.

Regarding my second question, so if i understand you correctly once the web gui is up and running i just need to open port 8081 to an IP address of my choice? I thought it may be more complicated than that.

**Comment by carlvonderheid** [comment]
They should be in <vectr_root>/logs.  <vectr_root> is /opt/vectr by default.

I meant that you can make the EC2 port accessible from a CIDR block using a Security Group (AWS shown):
![image](https://user-images.githubusercontent.com/34772348/88951361-dd9ef980-d263-11ea-81ef-9dae9f843f8e.png)

Setting a domain name to the node is probably out of scope for this.  The quick and dirty way to get running would be to add the public IP address of your EC2 (X.X.X.X) into your docker-compose.yml file under the tomcat service with a domain name (my_vectr_node in this example) of your choosing:
tomcat:
    extra_hosts:
      - "my_vectr_node:X.X.X.X"

(This is a yml file, be careful with spacing!)

Then on the host you're trying to access the site from, add an entry into your hosts file:
Windows: c:\Windows\System32\Drivers\etc\hosts
Linux: /etc/hosts
`X.X.X.X my_vectr_node`

**Comment by neil-fox** [comment]
Thanks Carl that's really useful to know regarding the yml file.

Regarding the logs that is the location i first checked before asking about where they were stored. The reason being is my logs folder is empty:

![image](https://user-images.githubusercontent.com/26876090/89014760-ea782780-d30d-11ea-9605-d603a05bcdb3.png)

Like i say i have followed the install instructions as per the docs website and even watched the video tutorial install.

**Comment by carlvonderheid** [comment]
Sounds like a permissions issue.  If you send your email address to vectrops@securityriskadvisors.com, I'll contact you to set up a screen share to take a look.

**Comment by neil-fox** [comment]
Hi,

I get the following message when I tried to email you.

![image](https://user-images.githubusercontent.com/26876090/89024874-bdcc0c00-d31d-11ea-87c7-9d247eea9327.png)

You can reach out to me at neil.p.fox@outlook.com

Thanks

**Comment by neil-fox** [comment]
Carl,

Thanks for your assistance with this, I have now been able to logon to the Web GUI.

For anybody else who comes across this issue, when i was updating the .env file it didn't like some of the special characters i was using for the passwords you have to set. This wasn't evident from using nano however when using vi you could see the colours of the text indicated that their was an issue.

The amendment to my yml file and windows hosts file also worked great to access the server over 8081 from an external IP.

Thanks again and keep up the great work.
