### ISSUE TITLE
Cannot use the Initial Delivery Phase or create new ones to be used in test cases.

### ISSUE THREAD

**Issue by deauth0x000c** [SecurityRiskAdvisors/VECTR#8]
If I create a test case with the phase "Initial Delivery" it will not save as a test case within a campaign.  This applies if I use built-in test cases or create a new one.  Also when creating a new Phase this will not permanently save as a test case within a campaign.

**Comment by carlvonderheid** [comment]
Can you make sure that you have that phase added to the kill chain that you are using in your assessment group?

**Comment by deauth0x000c** [comment]
That was it my apologies, I failed to check that setting.  Thank you and really enjoying this tool.
