### ISSUE TITLE
Assessment status stuck as "In Progress" #bug

### ISSUE THREAD

**Issue by gregohmyeggo** [SecurityRiskAdvisors/VECTR#84]
There is a bug with an Assessment status stuck as "In Progress" even though all Test Cases are shown as "Completed" and there are zero "Test Cases Not Completed" 

No items are set as "TBD" and all Test Cases include a Start and corresponding Stop Time

Version: 5.6.3

![2020-08-14 15_30_25-Start](https://user-images.githubusercontent.com/12466798/90297420-3e712900-de43-11ea-810c-e29dbe6d5cf2.png)

![2020-08-14 15_30_34-Start](https://user-images.githubusercontent.com/12466798/90297427-4335dd00-de43-11ea-9e35-e6b7d936d476.png)

**Comment by gregohmyeggo** [comment]
I was able to narrow down a possible source of the issue, but couldn't confirm it. I ended up going back through the Assessment and creating new Campaigns (matching the originals) one at a time. It seems like removing one of the Campaigns all for 'Persistence' phase, then saving fixed the issue.

Hope this helps on future cases like this.

**Comment by carlvonderheid** [comment]
Fixed in 8.2.0
