### ISSUE TITLE
What is the supported version of NAV LAYER import?

### ISSUE THREAD

**Issue by radiusmk** [SecurityRiskAdvisors/VECTR#88]
Hello;

I tried to import a new evaluation of a "NAV LAYER" that I created at https://mitre-attack.github.io/attack-navigator/enterprise/, but Vectr didn't recognize some fields in the json file, for example "layout" field .

Which version of Navigator should I use? 

Thanks. 
Marco Aurélio

**Comment by carlvonderheid** [comment]
Yea, sorry we didn't make that clearer.  The current released VECTR version (5.6.3) should use Attack Navigator Layer version 2.2.  We are shooting for a subtechnique supported VECTR release week of  August 31, which will then use Attack Navigator 3.x.
