### ISSUE TITLE
Documentation request to have an "Update" section

### ISSUE THREAD

**Issue by cmaenner** [SecurityRiskAdvisors/VECTR#9]
Could you please add in documentation showing how to upgrade our VECTR instance? We have an internal Docker Hub and if we had the steps to perform this action, it would be great!

For example:

- `docker build -f Dockerfile -t hub.company.net/group/sra_vectr_tomcat:x.x.x .`
- `docker login hub.company.net`
- `docker push hub.company.net/group/sra_vectr_tomcat:x.x.x`

Also, it would be nice for the community to understand if the organization does not have an internal Docker Hub how to add in arguments to utilize a proxy in case the server infrastructure does not have Internet activity.

Keep up the great work!

**Comment by thebleucheese** [comment]
Hi Chris, thanks for the feedback. We've added documentation for upgrade paths that should help users with straightforward installations.  

We're investigating different options for installations without direct internet connectivity and want to make sure we cover proxies as well as air-gapped installations.  Some of this may involve linking to the docker documentation as it's live and could include changes.  

Right now, it looks like the best path for proxied installations is supplying information in **~/.docker/config.json** before attempting to install or build VECTR and hope it works.  For some environments, we've found this is not enough and we've had to do everything from opening high-numbered TCP ports to providing proxy and configuration details to apt.conf inside the VECTR containers to prevent certificate issues.  We'll document these issues as they arise and work on getting them into the Wiki to help users.

I'm going to leave this issue open for now until we thoroughly test and document proxy solutions.

**Comment by thebleucheese** [comment]
The most recent VECTR release (5.5) has put VECTR images directly in dockerhub.  Downloading images from there and hosting locally in an image repository (if no connectivity) or downloading directly from dockerhub should be all that's needed to install now.  Closing unless we need to do further work on this.
