### ISSUE TITLE
Tool data not displaying in Reporting

### ISSUE THREAD

**Issue by SolAngelus** [SecurityRiskAdvisors/VECTR#91]
Good Afternoon, 
We've recently completed our first few assessments. Our Red and Blue teams have ensured all tool related boxes have been checked, but unfortunately tool data does not seem to be coming through.
![Annotation 2020-09-03 152341](https://user-images.githubusercontent.com/24551663/92158171-7f80ab80-edf9-11ea-87cc-e77da8421ef1.png)

Tool data appears for the other demo databases but not for ours. Unsure what I am missing.

**Comment by thebleucheese** [comment]
Hey sorry you're encountering a missing report, can you email vectrops@securityriskadvisors.com referencing this issue? It might be easiest to do a screenshare to figure out if there's either a bug in the system or missing data.

**Comment by SolAngelus** [comment]
I found that the Data Integrity panel (as suggested by the Vectr Ops team) within the Reporting Section was great for finding the holes in my data. Turns out my blue team missed some check boxes, as I didn't know to tell them to look for them or check them off. 

We've since gotten them marked appropriately and the Reporting panel is a fully operational battle-station once again!
