### ISSUE TITLE
5.7.0 upgrade doesn't populate Heat Map data.

### ISSUE THREAD

**Issue by gregohmyeggo** [SecurityRiskAdvisors/VECTR#92]
The upgrade to 5.7.0 doesn't populate Test Case data in the Heat Map report. The Test Case data DOES populate all other reports, but the Heat Map is "blank" (all grey). 

The demo DB "DEMO_PURPLE_CE" test case data DOES populate the Heat Map.

**Comment by thebleucheese** [comment]
You may need to change the Map Type from "Latest" to "Overall".  The "Latest" setting requires a Test Case Template to be set for Test Cases for them to be shown on the report. If Test Cases were created solely in the current local database and aren't mapped to a template in the Administration section this can occur.

Also check the "Data Integrity" report to see if anything is missing.

**Comment by gregohmyeggo** [comment]
That worked! 

Thanks for the quick response! I'll keep testing and report any other issues.
